# Generated by Django 5.2.7 on 2025-10-27 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('appelation', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_document', models.CharField(choices=[('CV', 'CV'), ('Contrat', 'Contrat'), ('Lettre', 'Lettre de motivation'), ('Autre', 'Autre')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents_employes/')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='personnel.employe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_banque', models.CharField(max_length=100)),
                ('numero_compte', models.CharField(max_length=50)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banque', to='personnel.employe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Identite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_carte_identite', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identite', to='personnel.employe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre_poste', models.CharField(max_length=100)),
                ('date_embauche', models.DateField()),
                ('type_contrat', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI')], max_length=50)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poste', to='personnel.employe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('num_cnaps', models.CharField(blank=True, max_length=50, null=True)),
                ('num_ostie', models.CharField(blank=True, max_length=50, null=True)),
                ('assurance_sante', models.CharField(blank=True, max_length=100, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='personnel.employe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
