# Generated by Django 5.2.7 on 2025-11-19 11:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationFamiliale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epoux_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('epoux_prenoms', models.CharField(blank=True, max_length=100, null=True)),
                ('epoux_date_naissance', models.DateField(blank=True, null=True)),
                ('epoux_lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('epoux_societe', models.CharField(blank=True, max_length=150, null=True)),
                ('epoux_fonction', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_prenoms', models.CharField(max_length=150)),
                ('sexe', models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('familiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='personnel.informationfamiliale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationPersonnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('sexe', models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, null=True)),
                ('appellation', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('CIN', models.CharField(blank=True, max_length=50, null=True)),
                ('date_CIN', models.DateField(blank=True, null=True)),
                ('lieu_CIN', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cnaps', models.CharField(blank=True, max_length=50, null=True)),
                ('ancien_numero_journaliere', models.CharField(blank=True, max_length=50, null=True)),
                ('pere', models.CharField(blank=True, max_length=100, null=True)),
                ('mere', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('quartier', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_employes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('photo_taille', models.PositiveIntegerField(blank=True, help_text='Taille du fichier en octets', null=True)),
                ('photo_type', models.CharField(blank=True, help_text='Extension du fichier', max_length=10, null=True)),
                ('photo_largeur', models.PositiveIntegerField(blank=True, help_text='Largeur en pixels', null=True)),
                ('photo_hauteur', models.PositiveIntegerField(blank=True, help_text='Hauteur en pixels', null=True)),
                ('photo_validee', models.BooleanField(default=False, help_text='Statut de validation de la photo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employes_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='informationfamiliale',
            name='employe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='familiale', to='personnel.informationpersonnelle'),
        ),
        migrations.CreateModel(
            name='InformationBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_banque', models.CharField(blank=True, max_length=100, null=True)),
                ('cle_rib', models.CharField(blank=True, max_length=10, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bancaire', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DossierPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='dossiers/cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='dossiers/lettres/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('residence', models.FileField(blank=True, null=True, upload_to='dossiers/residences/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('cin', models.FileField(blank=True, null=True, upload_to='dossiers/cin/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('carte_cnaps', models.FileField(blank=True, null=True, upload_to='dossiers/cnaps/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('rib', models.FileField(blank=True, null=True, upload_to='dossiers/rib/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('photo_identite', models.FileField(blank=True, null=True, upload_to='dossiers/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('certificat_travail', models.FileField(blank=True, null=True, upload_to='dossiers/certificats/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_personnel', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationSalairePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('responsable_section', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('indice', models.CharField(blank=True, help_text="Indice de l'employé", max_length=20, null=True)),
                ('taux_horaire', models.DecimalField(blank=True, decimal_places=2, help_text='Taux horaire en Ariary', max_digits=10, null=True)),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, help_text='Salaire de base en Ariary', max_digits=12, null=True)),
                ('autre_indemnite', models.DecimalField(blank=True, decimal_places=2, help_text='Autres indemnités en Ariary', max_digits=12, null=True)),
                ('prime_anciennete', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('indemnite_deplacement', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dernier_aug_indice', models.CharField(blank=True, max_length=50, null=True)),
                ('pour_30', models.CharField(blank=True, max_length=50, null=True)),
                ('salaire_total', models.DecimalField(blank=True, decimal_places=2, help_text='Salaire total calculé en Ariary', max_digits=12, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salaire_personnel', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retraite', models.CharField(blank=True, max_length=50, null=True)),
                ('enfant_allocation', models.IntegerField(blank=True, default=0, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sociale', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
