# Generated by Django 5.2.7 on 2025-10-28 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationPersonnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('CIN', models.CharField(blank=True, max_length=50, null=True)),
                ('date_lieu_CIN', models.CharField(blank=True, max_length=100, null=True)),
                ('pere', models.CharField(blank=True, max_length=100, null=True)),
                ('mere', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_money', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='identite',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='social',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='poste',
            name='employe',
        ),
        migrations.CreateModel(
            name='InformationComplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('maison', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_rapide', models.CharField(blank=True, max_length=100, null=True)),
                ('dernier_aug_indice', models.CharField(blank=True, max_length=50, null=True)),
                ('pour_30', models.CharField(blank=True, max_length=50, null=True)),
                ('T1_17', models.CharField(blank=True, max_length=50, null=True)),
                ('obs_prime', models.TextField(blank=True, null=True)),
                ('enquete', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complementaire', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_banque', models.CharField(max_length=100)),
                ('code_banque', models.CharField(max_length=50)),
                ('code_agence', models.CharField(max_length=50)),
                ('numero_compte', models.CharField(max_length=50)),
                ('cle_rib', models.CharField(max_length=10)),
                ('banque_beneficiaire', models.CharField(blank=True, max_length=100, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bancaire', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationProfessionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fonction', models.CharField(max_length=100)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('appellation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('date_debauche', models.DateField(blank=True, null=True)),
                ('ancien_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('titre_poste', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('secteur', models.CharField(blank=True, max_length=100, null=True)),
                ('code_fonction', models.CharField(blank=True, max_length=50, null=True)),
                ('section_temporaraire', models.CharField(blank=True, max_length=100, null=True)),
                ('pour_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('depart', models.CharField(blank=True, max_length=100, null=True)),
                ('motif_depart', models.TextField(blank=True, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professionnelle', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_cnaps', models.CharField(blank=True, max_length=50, null=True)),
                ('retraite', models.CharField(blank=True, max_length=50, null=True)),
                ('enfant_allocation', models.IntegerField(default=0)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sociale', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Banque',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Identite',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.DeleteModel(
            name='Poste',
        ),
    ]
