# Generated by Django 5.2.7 on 2025-11-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationsalairepersonnel',
            name='pour_30',
        ),
    ]
