# Generated by Django 5.2.7 on 2025-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_informationpersonnelle_remove_document_employe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationcomplementaire',
            name='email',
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
