# Generated by Django 5.2.7 on 2025-10-31 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_remove_informationcomplementaire_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationbancaire',
            name='cle_rib',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='informationbancaire',
            name='code_agence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informationbancaire',
            name='code_banque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informationbancaire',
            name='nom_banque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informationbancaire',
            name='numero_compte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='sexe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informationsociale',
            name='enfant_allocation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
