# Generated by Django 5.2.7 on 2025-11-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_alter_informationpersonnelle_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationpersonnelle',
            old_name='nom',
            new_name='nom_complet',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='prenoms',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='quartier',
        ),
    ]
