# Generated by Django 5.2.7 on 2025-10-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_alter_informationbancaire_cle_rib_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, null=True),
        ),
    ]
