# Generated by Django 5.2.7 on 2025-11-22 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_rename_nom_informationpersonnelle_nom_complet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('responsable_section', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, max_length=10, null=True)),
                ('indice', models.CharField(blank=True, max_length=20, null=True)),
                ('taux_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('autre_indemnite', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prime_anciennete', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('indemnite_deplacement', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dernier_aug_indice', models.CharField(blank=True, max_length=50, null=True)),
                ('salaire_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, help_text='Raison de la modification', null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_salaire', to='personnel.informationpersonnelle')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_salariales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Salarial',
                'verbose_name_plural': 'Historiques Salariaux',
                'ordering': ['-date_modification'],
            },
        ),
    ]
