# Generated by Django 5.2.7 on 2025-10-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_alter_informationpersonnelle_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationprofessionnelle',
            name='appellation',
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='appellation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
