# Generated by Django 5.2.7 on 2025-10-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_remove_informationprofessionnelle_appellation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationprofessionnelle',
            name='fonction',
        ),
        migrations.RemoveField(
            model_name='informationprofessionnelle',
            name='section',
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
