# Generated by Django 5.2.7 on 2025-11-22 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_historiquesalarial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_changement', models.DateField(auto_now_add=True)),
                ('motif', models.CharField(blank=True, help_text='Motif du changement', max_length=255, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('responsable_section', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], max_length=10, null=True)),
                ('indice', models.CharField(blank=True, max_length=20, null=True)),
                ('taux_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('autre_indemnite', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prime_anciennete', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('indemnite_deplacement', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dernier_aug_indice', models.CharField(blank=True, max_length=50, null=True)),
                ('salaire_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_salaire', to=settings.AUTH_USER_MODEL)),
                ('salaire_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='personnel.informationsalairepersonnel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HistoriqueSalarial',
        ),
    ]
