# Generated by Django 5.2.7 on 2025-11-24 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_historiquesalaire_delete_historiquesalarial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiquesalaire',
            old_name='salaire_personnel',
            new_name='salaire',
        ),
        migrations.RemoveField(
            model_name='historiquesalaire',
            name='date_changement',
        ),
        migrations.RemoveField(
            model_name='historiquesalaire',
            name='motif',
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='motif_modification',
            field=models.TextField(blank=True, help_text='Raison de la modification', null=True),
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='type_modification',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression')], default='MODIFICATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='historiquesalaire',
            name='modifie_par',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modifications_salaire', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LogModificationSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champ_modifie', models.CharField(max_length=100)),
                ('ancienne_valeur', models.TextField(blank=True, null=True)),
                ('nouvelle_valeur', models.TextField(blank=True, null=True)),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_champs', to='personnel.historiquesalaire')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
