# Generated by Django 5.2.7 on 2025-10-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_remove_informationprofessionnelle_fonction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationprofessionnelle',
            old_name='section_temporaraire',
            new_name='section_temporaire',
        ),
    ]
