# Generated by Django 5.2.7 on 2025-11-25 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_rename_salaire_personnel_historiquesalaire_salaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiquesalaire',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historique de salaire', 'verbose_name_plural': 'Historiques de salaires'},
        ),
        migrations.RemoveField(
            model_name='historiquesalaire',
            name='motif_modification',
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Commentaire sur la modification', null=True),
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='employe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historique_salaires', to='personnel.informationpersonnelle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiquesalaire',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_salaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LogModificationSalaire',
        ),
    ]
