# Generated by Django 5.2.7 on 2025-11-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_rename_section_temporaraire_informationprofessionnelle_section_temporaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationpersonnelle',
            old_name='mobile_money',
            new_name='ancien_numero',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='informationprofessionnelle',
            name='ancien_numero',
        ),
        migrations.RemoveField(
            model_name='informationsociale',
            name='numero_cnaps',
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='numero_cnaps',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='quartier',
            field=models.TextField(blank=True, null=True),
        ),
    ]
