# Generated by Django 5.2.7 on 2025-11-25 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_alter_historiquesalaire_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiquesalaire',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historique de salaire', 'verbose_name_plural': 'Historiques de salaire'},
        ),
        migrations.RenameField(
            model_name='historiquesalaire',
            old_name='autre_indemnite',
            new_name='ancien_salaire_base',
        ),
        migrations.RenameField(
            model_name='historiquesalaire',
            old_name='indemnite_deplacement',
            new_name='ancien_salaire_total',
        ),
        migrations.RenameField(
            model_name='historiquesalaire',
            old_name='taux_horaire',
            new_name='ancien_taux_horaire',
        ),
        migrations.RenameField(
            model_name='historiquesalaire',
            old_name='prime_anciennete',
            new_name='ancienne_autre_indemnite',
        ),
        migrations.RenameField(
            model_name='historiquesalaire',
            old_name='salaire_base',
            new_name='ancienne_indemnite_deplacement',
        ),
        migrations.RenameField(
            model_name='historiquesalaire',
            old_name='indice',
            new_name='ancienne_indice',
        ),
        migrations.RenameField(
            model_name='historiquesalaire',
            old_name='salaire_total',
            new_name='ancienne_prime_anciennete',
        ),
        migrations.RemoveField(
            model_name='historiquesalaire',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='historiquesalaire',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='historiquesalaire',
            name='dernier_aug_indice',
        ),
        migrations.RemoveField(
            model_name='historiquesalaire',
            name='responsable_section',
        ),
        migrations.RemoveField(
            model_name='historiquesalaire',
            name='salaire',
        ),
        migrations.RemoveField(
            model_name='historiquesalaire',
            name='type_modification',
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='ancienne_categorie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='nouveau_salaire_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='nouveau_salaire_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='nouveau_taux_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='nouvelle_autre_indemnite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='nouvelle_categorie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='nouvelle_indemnite_deplacement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='nouvelle_indice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='nouvelle_prime_anciennete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='historiquesalaire',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiquesalaire',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_salaire', to='personnel.informationpersonnelle'),
        ),
        migrations.AlterField(
            model_name='historiquesalaire',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_salaire', to=settings.AUTH_USER_MODEL),
        ),
    ]
