# Generated by Django 5.2.7 on 2025-11-03 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_rename_mobile_money_informationpersonnelle_ancien_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='dossiers/cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='dossiers/lettres/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('residence', models.FileField(blank=True, null=True, upload_to='dossiers/residences/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('cin', models.FileField(blank=True, null=True, upload_to='dossiers/cin/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('carte_cnaps', models.FileField(blank=True, null=True, upload_to='dossiers/cnaps/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('rib', models.FileField(blank=True, null=True, upload_to='dossiers/rib/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('photo_identite', models.FileField(blank=True, null=True, upload_to='dossiers/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('certificat_travail', models.FileField(blank=True, null=True, upload_to='dossiers/certificats/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_personnel', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
