# Generated by Django 5.2.7 on 2025-11-04 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_dossierpersonnel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationpersonnelle',
            old_name='date_lieu_CIN',
            new_name='date_CIN',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='ancien_numero',
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='ancien_numero_journaliere',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='lieu_CIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InformationFamiliale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epoux_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('epoux_prenoms', models.CharField(blank=True, max_length=100, null=True)),
                ('epoux_date_naissance', models.DateField(blank=True, null=True)),
                ('epoux_lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('epoux_societe', models.CharField(blank=True, max_length=150, null=True)),
                ('epoux_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='familiale', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_prenoms', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('familiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='personnel.informationfamiliale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
