# Generated by Django 5.2.7 on 2025-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_alter_historiquesalaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationbancaire',
            name='cle_rib',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
