# Generated by Django 5.2.7 on 2025-11-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_rename_date_lieu_cin_informationpersonnelle_date_cin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='date_CIN',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InformationSalairePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, max_length=50, null=True)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable_section', models.CharField(blank=True, max_length=100, null=True)),
                ('prime_anciennete', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('indemnite_deplacement', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dernier_aug_indice', models.CharField(blank=True, max_length=50, null=True)),
                ('pour_30', models.CharField(blank=True, max_length=50, null=True)),
                ('T1_17', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('T2_17', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('T3_17', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('T4_17', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('obs_prime', models.TextField(blank=True, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salaire_personnel', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='InformationComplementaire',
        ),
    ]
