# Generated by Django 5.2.7 on 2025-12-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_alter_informationbancaire_cle_rib'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpersonnelle',
            name='responsable',
            field=models.CharField(blank=True, choices=[('', 'Sélectionnez un responsable'), ('RESPONSABLE 0', 'Responsable 0'), ('RESPONSABLE 1', 'Responsable 1'), ('RESPONSABLE 2', 'Responsable 2'), ('RESPONSABLE 3', 'Responsable 3'), ('RESPONSABLE RAPHIA', 'Responsable Raphia')], help_text='Responsable de la section', max_length=50, null=True),
        ),
    ]
