# Generated by Django 5.2.7 on 2025-12-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_informationpersonnelle_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpersonnelle',
            name='date_duplicata',
            field=models.DateField(blank=True, null=True, verbose_name='Date du duplicata'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='duplicata_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro du duplicata'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='has_cin',
            field=models.BooleanField(default=False, verbose_name="Carte Nationale d'Identité (CIN)"),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='has_duplicata',
            field=models.BooleanField(default=False, verbose_name='Duplicata de CIN'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='has_passport',
            field=models.BooleanField(default=False, verbose_name='Passeport'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='has_permis',
            field=models.BooleanField(default=False, verbose_name='Permis de conduire'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='has_permis_a',
            field=models.BooleanField(default=False, verbose_name='Permis A'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='has_permis_b',
            field=models.BooleanField(default=False, verbose_name='Permis B'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='has_permis_c',
            field=models.BooleanField(default=False, verbose_name='Permis C'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='has_permis_d',
            field=models.BooleanField(default=False, verbose_name='Permis D'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='has_permis_e',
            field=models.BooleanField(default=False, verbose_name='Permis E'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='has_permis_g',
            field=models.BooleanField(default=False, verbose_name='Permis G'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='lieu_duplicata',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu du duplicata'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='passport_code_pays',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code pays'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='passport_date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='passport_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de passeport'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='passport_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type de passeport'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_a_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date permis A'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_b_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date permis B'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_c_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date permis C'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_d_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date permis D'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_e_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date permis E'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_g_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date permis G'),
        ),
    ]
