# Generated by Django 5.2.7 on 2025-11-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_alter_informationpersonnelle_date_cin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformationProfessionnelle',
        ),
    ]
