# Generated by Django 5.2.7 on 2025-11-12 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_delete_informationprofessionnelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpersonnelle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_employes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='photo_hauteur',
            field=models.PositiveIntegerField(blank=True, help_text='Hauteur en pixels', null=True),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='photo_largeur',
            field=models.PositiveIntegerField(blank=True, help_text='Largeur en pixels', null=True),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='photo_taille',
            field=models.PositiveIntegerField(blank=True, help_text='Taille du fichier en octets', null=True),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='photo_type',
            field=models.CharField(blank=True, help_text='Extension du fichier', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='photo_validee',
            field=models.BooleanField(default=False, help_text='Statut de validation de la photo'),
        ),
    ]
