# Generated by Django 5.2.7 on 2025-12-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_remove_informationpersonnelle_fonction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationsalairepersonnel',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='informationsalairepersonnel',
            name='responsable_section',
        ),
    ]
