# Generated by Django 5.2.7 on 2025-11-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_informationpersonnelle_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, null=True),
        ),
    ]
