# Generated by Django 5.2.7 on 2025-12-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0015_remove_informationsalairepersonnel_date_embauche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='date_duplicata',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='duplicata_numero',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='has_cin',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='has_duplicata',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='has_passport',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='has_permis',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='has_permis_a',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='has_permis_b',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='has_permis_c',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='has_permis_d',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='has_permis_e',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='has_permis_g',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='lieu_duplicata',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='passport_code_pays',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='passport_date_expiration',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='passport_numero',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='passport_type',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='permis_a_date',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='permis_b_date',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='permis_c_date',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='permis_d_date',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='permis_e_date',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='permis_g_date',
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='numero_cnaps',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='responsable',
            field=models.CharField(blank=True, choices=[('', 'Sélectionnez un responsable'), ('RESPONSABLE 0', 'Responsable 0'), ('RESPONSABLE 1', 'Responsable 1'), ('RESPONSABLE 2', 'Responsable 2'), ('RESPONSABLE 3', 'Responsable 3'), ('RESPONSABLE RAPHIA', 'Responsable Raphia')], help_text='Responsable de la section', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='section',
            field=models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BRODERIE MACHINE', 'BRODERIE MACHINE'), ('BRODERIE MAIN AK17', 'BRODERIE MAIN AK17'), ('BRODERIE MAIN DEV', 'BRODERIE MAIN DEV'), ('BUREAU DE METHODE', 'BUREAU DE METHODE'), ('CONTROLE QUALITE AS', 'CONTROLE QUALITE AS'), ('CHAINE 1', 'CHAINE 1'), ('CHAINE 2', 'CHAINE 2'), ('CHAINE 3', 'CHAINE 3'), ('CHAINE 4', 'CHAINE 4'), ('CHAINE 5', 'CHAINE 5'), ('CHAINE 6', 'CHAINE 6'), ('CHAINE 7', 'CHAINE 7'), ('CHAINE 8', 'CHAINE 8'), ('CHAINE 9', 'CHAINE 9'), ('CHAINE 10', 'CHAINE 10'), ('CHAINE 11', 'CHAINE 11'), ('CHAINE 12', 'CHAINE 12'), ('CHAINE CUIR', 'CHAINE CUIR'), ('COLLECTION', 'COLLECTION'), ('COUPE', 'COUPE'), ('COUPE COLLECTION', 'COUPE COLLECTION'), ('FINITION D', 'FINITION D'), ('FINITION M', 'FINITION M'), ('FINITION P', 'FINITION P'), ('FINITION Q', 'FINITION Q'), ('FINITION R', 'FINITION R'), ('LECTRA', 'LECTRA'), ('LEMARIE HVA', 'LEMARIE HVA'), ('MAINTENANCE', 'MAINTENANCE'), ('MAISON', 'MAISON'), ('PACKING/EXPEDITION', 'PACKING/EXPEDITION'), ('PLISSE', 'PLISSE'), ('POLE QUALITE 1', 'POLE QUALITE 1'), ('POLE QUALITE 2', 'POLE QUALITE 2'), ('RAPHIA 1', 'RAPHIA 1'), ('RAPHIA 2', 'RAPHIA 2'), ('RAPHIA 3', 'RAPHIA 3'), ('RAPHIA 4', 'RAPHIA 4'), ('RAPHIA 5', 'RAPHIA 5'), ('RAPHIA 6', 'RAPHIA 6'), ('RESPONSABLE 0', 'RESPONSABLE 0'), ('RESPONSABLE 1', 'RESPONSABLE 1'), ('RESPONSABLE 2', 'RESPONSABLE 2'), ('RESPONSABLE 3', 'RESPONSABLE 3'), ('RESPONSABLE RAPHIA', 'RESPONSABLE RAPHIA'), ('SECURITE', 'SECURITE')], help_text="Section de l'employé", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informationsalairepersonnel',
            name='categorie',
            field=models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], help_text="Catégorie de l'employé", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='informationsalairepersonnel',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informationsalairepersonnel',
            name='responsable_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='InformationProfessionnelle',
        ),
    ]
