# Generated by Django 5.2.7 on 2025-12-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0016_remove_informationpersonnelle_date_duplicata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='fonction',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='numero_cnaps',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='informationpersonnelle',
            name='section',
        ),
        migrations.RemoveField(
            model_name='informationsalairepersonnel',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='informationsalairepersonnel',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='informationsalairepersonnel',
            name='responsable_section',
        ),
        migrations.CreateModel(
            name='InformationProfessionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_embauche', models.DateField(blank=True, help_text="Date d'embauche de l'employé", null=True)),
                ('fonction', models.CharField(blank=True, help_text='Fonction ou poste occupé', max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], help_text="Catégorie professionnelle de l'employé", max_length=10, null=True)),
                ('section', models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BRODERIE MACHINE', 'BRODERIE MACHINE'), ('BRODERIE MAIN AK17', 'BRODERIE MAIN AK17'), ('BRODERIE MAIN DEV', 'BRODERIE MAIN DEV'), ('BUREAU DE METHODE', 'BUREAU DE METHODE'), ('CONTROLE QUALITE AS', 'CONTROLE QUALITE AS'), ('CHAINE 1', 'CHAINE 1'), ('CHAINE 2', 'CHAINE 2'), ('CHAINE 3', 'CHAINE 3'), ('CHAINE 4', 'CHAINE 4'), ('CHAINE 5', 'CHAINE 5'), ('CHAINE 6', 'CHAINE 6'), ('CHAINE 7', 'CHAINE 7'), ('CHAINE 8', 'CHAINE 8'), ('CHAINE 9', 'CHAINE 9'), ('CHAINE 10', 'CHAINE 10'), ('CHAINE 11', 'CHAINE 11'), ('CHAINE 12', 'CHAINE 12'), ('CHAINE CUIR', 'CHAINE CUIR'), ('COLLECTION', 'COLLECTION'), ('COUPE', 'COUPE'), ('COUPE COLLECTION', 'COUPE COLLECTION'), ('FINITION D', 'FINITION D'), ('FINITION M', 'FINITION M'), ('FINITION P', 'FINITION P'), ('FINITION Q', 'FINITION Q'), ('FINITION R', 'FINITION R'), ('LECTRA', 'LECTRA'), ('LEMARIE HVA', 'LEMARIE HVA'), ('MAINTENANCE', 'MAINTENANCE'), ('MAISON', 'MAISON'), ('PACKING/EXPEDITION', 'PACKING/EXPEDITION'), ('PLISSE', 'PLISSE'), ('POLE QUALITE 1', 'POLE QUALITE 1'), ('POLE QUALITE 2', 'POLE QUALITE 2'), ('RAPHIA 1', 'RAPHIA 1'), ('RAPHIA 2', 'RAPHIA 2'), ('RAPHIA 3', 'RAPHIA 3'), ('RAPHIA 4', 'RAPHIA 4'), ('RAPHIA 5', 'RAPHIA 5'), ('RAPHIA 6', 'RAPHIA 6'), ('RESPONSABLE 0', 'RESPONSABLE 0'), ('RESPONSABLE 1', 'RESPONSABLE 1'), ('RESPONSABLE 2', 'RESPONSABLE 2'), ('RESPONSABLE 3', 'RESPONSABLE 3'), ('RESPONSABLE RAPHIA', 'RESPONSABLE RAPHIA'), ('SECURITE', 'SECURITE')], help_text="Section/département de l'employé", max_length=50, null=True)),
                ('responsable_section', models.CharField(blank=True, help_text='Nom du responsable de la section', max_length=100, null=True)),
                ('numero_cnaps', models.CharField(blank=True, help_text='Numéro CNAPS (Caisse Nationale de Prévoyance Sociale)', max_length=50, null=True, verbose_name='Numéro CNAPS')),
                ('numero_ostie', models.CharField(blank=True, help_text='Numéro OSTIE (Organisme de Santé et de Travail pour les Indépendants et Employés)', max_length=50, null=True, verbose_name='Numéro OSTIE')),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information_professionnelle', to='personnel.informationpersonnelle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
