# Generated by Django 5.2.7 on 2025-12-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0017_remove_informationpersonnelle_fonction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquesalaire',
            name='ancienne_categorie',
        ),
        migrations.RemoveField(
            model_name='historiquesalaire',
            name='nouvelle_categorie',
        ),
    ]
