# Generated by Django 5.2.7 on 2025-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0018_remove_historiquesalaire_ancienne_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpersonnelle',
            name='a_duplicata',
            field=models.BooleanField(default=False, verbose_name='Duplicata'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='a_passeport',
            field=models.BooleanField(default=False, verbose_name='Passeport'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='a_permis',
            field=models.BooleanField(default=False, verbose_name='Permis'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='code_pays_passeport',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Code pays passeport'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='date_duplicata',
            field=models.DateField(blank=True, null=True, verbose_name='Date du duplicata'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='date_expiration_passeport',
            field=models.DateField(blank=True, null=True, verbose_name='Date expiration passeport'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='lieu_duplicata',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu du duplicata'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='numero_passeport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro passeport'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_a_date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Date expiration Permis A'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_a_date_obtention',
            field=models.DateField(blank=True, null=True, verbose_name='Date obtention Permis A'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_b_date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Date expiration Permis B'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_b_date_obtention',
            field=models.DateField(blank=True, null=True, verbose_name='Date obtention Permis B'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_c_date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Date expiration Permis C'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_c_date_obtention',
            field=models.DateField(blank=True, null=True, verbose_name='Date obtention Permis C'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_a',
            field=models.BooleanField(default=False, verbose_name='Permis Catégorie A'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_b',
            field=models.BooleanField(default=False, verbose_name='Permis Catégorie B'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_c',
            field=models.BooleanField(default=False, verbose_name='Permis Catégorie C'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_d',
            field=models.BooleanField(default=False, verbose_name='Permis Catégorie D'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_e',
            field=models.BooleanField(default=False, verbose_name='Permis Catégorie E'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_f',
            field=models.BooleanField(default=False, verbose_name='Permis Catégorie F'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_d_date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Date expiration Permis D'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_d_date_obtention',
            field=models.DateField(blank=True, null=True, verbose_name='Date obtention Permis D'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_e_date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Date expiration Permis E'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_e_date_obtention',
            field=models.DateField(blank=True, null=True, verbose_name='Date obtention Permis E'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_f_date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Date expiration Permis F'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_f_date_obtention',
            field=models.DateField(blank=True, null=True, verbose_name='Date obtention Permis F'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='type_passeport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type passeport'),
        ),
    ]
