# Generated by Django 5.2.7 on 2025-12-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0020_remove_informationpersonnelle_a_duplicata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpersonnelle',
            name='code_pays_passport',
            field=models.CharField(blank=True, help_text='Code pays du passport (ex: MDG, FRA)', max_length=3, null=True, verbose_name='Code pays'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='date_duplicata',
            field=models.DateField(blank=True, null=True, verbose_name='Date du duplicata'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='date_expiration_passport',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration du passport"),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='lieu_duplicata',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu du duplicata'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='numero_passport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de passport'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_a',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis A", null=True, verbose_name='Permis Catégorie A'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_b',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis B", null=True, verbose_name='Permis Catégorie B'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_c',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis C", null=True, verbose_name='Permis Catégorie C'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_d',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis D", null=True, verbose_name='Permis Catégorie D'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_e',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis E", null=True, verbose_name='Permis Catégorie E'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='permis_categorie_f',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis F", null=True, verbose_name='Permis Catégorie F'),
        ),
        migrations.AddField(
            model_name='informationpersonnelle',
            name='type_passport',
            field=models.CharField(blank=True, help_text='Type de passport (ex: Ordinaire, Diplomatique)', max_length=20, null=True, verbose_name='Type de passport'),
        ),
    ]
