# Generated by Django 5.2.7 on 2025-12-04 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0021_informationpersonnelle_code_pays_passport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_competence', models.CharField(help_text='Nom de la compétence', max_length=100)),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('EXPERT', 'Expert')], default='DEBUTANT', max_length=20)),
                ('date_acquisition', models.DateField(help_text="Date d'acquisition de la compétence")),
                ('certifie', models.BooleanField(default=False, help_text='Compétence certifiée')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='personnel.informationpersonnelle')),
            ],
            options={
                'verbose_name': 'Compétence employé',
                'verbose_name_plural': 'Compétences employés',
            },
        ),
        migrations.CreateModel(
            name='EvolutionPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_evolution', models.CharField(choices=[('PROMOTION', 'Promotion'), ('MUTATION', 'Mutation'), ('CHANGEMENT_SECTION', 'Changement de section'), ('CHANGEMENT_CATEGORIE', 'Changement de catégorie'), ('AUTRE', 'Autre')], help_text="Type d'évolution professionnelle", max_length=30)),
                ('date_evolution', models.DateField(help_text='Date effective du changement')),
                ('ancienne_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('ancienne_categorie', models.CharField(blank=True, max_length=10, null=True)),
                ('ancienne_section', models.CharField(blank=True, max_length=50, null=True)),
                ('ancien_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('nouvelle_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('nouvelle_categorie', models.CharField(blank=True, max_length=10, null=True)),
                ('nouvelle_section', models.CharField(blank=True, max_length=50, null=True)),
                ('nouveau_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('augmentation_salaire', models.DecimalField(blank=True, decimal_places=2, help_text="Montant de l'augmentation liée à l'évolution (en Ariary)", max_digits=12, null=True)),
                ('pourcentage_augmentation', models.DecimalField(blank=True, decimal_places=2, help_text="Pourcentage d'augmentation", max_digits=5, null=True)),
                ('motif', models.TextField(help_text="Motif ou raison de l'évolution")),
                ('commentaire', models.TextField(blank=True, help_text='Commentaires additionnels', null=True)),
                ('date_validation', models.DateTimeField(blank=True, help_text="Date de validation de l'évolution", null=True)),
                ('document_justificatif', models.FileField(blank=True, help_text='Document justificatif (décision, note de service, etc.)', null=True, upload_to='evolutions_poste/')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions_poste', to='personnel.informationpersonnelle')),
                ('valide_par', models.ForeignKey(help_text="Utilisateur ayant validé l'évolution", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évolution de poste',
                'verbose_name_plural': 'Évolutions de poste',
                'ordering': ['-date_evolution', '-created_at'],
            },
        ),
    ]
