# Generated by Django 5.2.7 on 2025-12-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0022_competenceemploye_evolutionposte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolutionposte',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='evolutionposte',
            name='valide_par',
        ),
        migrations.DeleteModel(
            name='CompetenceEmploye',
        ),
        migrations.DeleteModel(
            name='EvolutionPoste',
        ),
    ]
