# Generated by Django 5.2.7 on 2025-12-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0023_remove_evolutionposte_employe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationprofessionnelle',
            name='categorie',
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='ancienne_categorie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historiquesalaire',
            name='nouvelle_categorie',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='informationsalairepersonnel',
            name='categorie',
            field=models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], help_text="Catégorie professionnelle de l'employé", max_length=10, null=True),
        ),
    ]
