# Generated by Django 5.2.7 on 2025-12-05 07:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0024_remove_informationprofessionnelle_categorie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_evolution', models.CharField(choices=[('PROMOTION', 'Promotion'), ('MUTATION', 'Mutation'), ('CHANGEMENT_SECTION', 'Changement de section'), ('CHANGEMENT_RESPONSABLE', 'Changement de responsable'), ('AUTRE', 'Autre')], max_length=30, verbose_name="Type d'évolution")),
                ('date_effective', models.DateField(help_text='Date à laquelle le changement prend effet', verbose_name="Date d'effet")),
                ('ancienne_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('ancienne_section', models.CharField(blank=True, max_length=50, null=True)),
                ('ancien_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('nouvelle_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('nouvelle_section', models.CharField(blank=True, max_length=50, null=True)),
                ('nouveau_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('motif', models.TextField(blank=True, help_text="Raison de l'évolution (promotion méritée, réorganisation, etc.)", null=True, verbose_name='Motif du changement')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('document_justificatif', models.FileField(blank=True, help_text='Note de service, lettre de promotion, etc.', null=True, upload_to='evolutions_poste/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Document justificatif')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions_poste', to='personnel.informationpersonnelle')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Évolution de poste',
                'verbose_name_plural': 'Évolutions de poste',
                'ordering': ['-date_effective', '-created_at'],
            },
        ),
    ]
