# Generated by Django 5.2.7 on 2025-12-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0025_evolutionposte'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolutionposte',
            name='ancienne_categorie',
            field=models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='evolutionposte',
            name='nouvelle_categorie',
            field=models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='type_evolution',
            field=models.CharField(choices=[('PROMOTION', 'Promotion'), ('MUTATION', 'Mutation'), ('CHANGEMENT_SECTION', 'Changement de section'), ('CHANGEMENT_RESPONSABLE', 'Changement de responsable'), ('CHANGEMENT_CATEGORIE', 'Changement de catégorie'), ('AUTRE', 'Autre')], max_length=30, verbose_name="Type d'évolution"),
        ),
    ]
