# Generated by Django 5.2.7 on 2025-12-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0026_evolutionposte_ancienne_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationprofessionnelle',
            name='responsable',
            field=models.CharField(blank=True, choices=[('', 'Sélectionnez un responsable'), ('RESPONSABLE 0', 'Responsable 0'), ('RESPONSABLE 1', 'Responsable 1'), ('RESPONSABLE 2', 'Responsable 2'), ('RESPONSABLE 3', 'Responsable 3'), ('RESPONSABLE RAPHIA', 'Responsable Raphia')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='EvolutionPoste',
        ),
    ]
