# Generated by Django 5.2.7 on 2025-12-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0029_evolutionposte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvolutionPoste',
        ),
    ]
