# Generated by Django 5.2.7 on 2025-12-09 12:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0030_delete_evolutionposte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_evolution', models.CharField(choices=[('PROMOTION', 'Promotion'), ('MUTATION', 'Mutation'), ('CHANGEMENT_FONCTION', 'Changement de fonction'), ('CHANGEMENT_CATEGORIE', 'Changement de catégorie'), ('CHANGEMENT_SECTION', 'Changement de section')], help_text="Type d'évolution professionnelle", max_length=30)),
                ('date_evolution', models.DateField(help_text='Date effective du changement')),
                ('ancienne_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('ancienne_section', models.CharField(blank=True, max_length=50, null=True)),
                ('ancienne_categorie', models.CharField(blank=True, max_length=10, null=True)),
                ('ancien_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('nouvelle_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('nouvelle_section', models.CharField(blank=True, max_length=50, null=True)),
                ('nouvelle_categorie', models.CharField(blank=True, max_length=10, null=True)),
                ('nouveau_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('motif', models.TextField(blank=True, help_text="Motif de l'évolution (promotion, réorganisation, etc.)", null=True)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaires ou observations', null=True)),
                ('document_justificatif', models.FileField(blank=True, help_text="Document justifiant l'évolution (note de service, etc.)", null=True, upload_to='evolutions_poste/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions_poste', to='personnel.informationpersonnelle')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évolution de poste',
                'verbose_name_plural': 'Évolutions de poste',
                'ordering': ['-date_evolution', '-created_at'],
            },
        ),
    ]
