# Generated by Django 5.2.7 on 2025-12-09 13:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0032_delete_evolutionposte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_evolution', models.CharField(choices=[('PROMOTION', 'Promotion'), ('CHANGEMENT_SECTION', 'Changement de Section'), ('CHANGEMENT_FONCTION', 'Changement de Fonction'), ('CHANGEMENT_CATEGORIE', 'Changement de Catégorie'), ('CHANGEMENT_RESPONSABLE', 'Changement de Responsable'), ('AUTRE', 'Autre')], default='PROMOTION', max_length=30)),
                ('date_effet', models.DateField(help_text="Date à partir de laquelle l'évolution est effective")),
                ('ancienne_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('ancienne_categorie', models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], max_length=10, null=True)),
                ('ancienne_section', models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BRODERIE MACHINE', 'BRODERIE MACHINE'), ('BRODERIE MAIN AK17', 'BRODERIE MAIN AK17'), ('BRODERIE MAIN DEV', 'BRODERIE MAIN DEV'), ('BUREAU DE METHODE', 'BUREAU DE METHODE'), ('CONTROLE QUALITE AS', 'CONTROLE QUALITE AS'), ('CHAINE 1', 'CHAINE 1'), ('CHAINE 2', 'CHAINE 2'), ('CHAINE 3', 'CHAINE 3'), ('CHAINE 4', 'CHAINE 4'), ('CHAINE 5', 'CHAINE 5'), ('CHAINE 6', 'CHAINE 6'), ('CHAINE 7', 'CHAINE 7'), ('CHAINE 8', 'CHAINE 8'), ('CHAINE 9', 'CHAINE 9'), ('CHAINE 10', 'CHAINE 10'), ('CHAINE 11', 'CHAINE 11'), ('CHAINE 12', 'CHAINE 12'), ('CHAINE CUIR', 'CHAINE CUIR'), ('COLLECTION', 'COLLECTION'), ('COUPE', 'COUPE'), ('COUPE COLLECTION', 'COUPE COLLECTION'), ('FINITION D', 'FINITION D'), ('FINITION M', 'FINITION M'), ('FINITION P', 'FINITION P'), ('FINITION Q', 'FINITION Q'), ('FINITION R', 'FINITION R'), ('LECTRA', 'LECTRA'), ('LEMARIE HVA', 'LEMARIE HVA'), ('MAINTENANCE', 'MAINTENANCE'), ('MAISON', 'MAISON'), ('PACKING/EXPEDITION', 'PACKING/EXPEDITION'), ('PLISSE', 'PLISSE'), ('POLE QUALITE 1', 'POLE QUALITE 1'), ('POLE QUALITE 2', 'POLE QUALITE 2'), ('RAPHIA 1', 'RAPHIA 1'), ('RAPHIA 2', 'RAPHIA 2'), ('RAPHIA 3', 'RAPHIA 3'), ('RAPHIA 4', 'RAPHIA 4'), ('RAPHIA 5', 'RAPHIA 5'), ('RAPHIA 6', 'RAPHIA 6'), ('RESPONSABLE 0', 'RESPONSABLE 0'), ('RESPONSABLE 1', 'RESPONSABLE 1'), ('RESPONSABLE 2', 'RESPONSABLE 2'), ('RESPONSABLE 3', 'RESPONSABLE 3'), ('RESPONSABLE RAPHIA', 'RESPONSABLE RAPHIA'), ('SECURITE', 'SECURITE')], max_length=50, null=True)),
                ('ancien_responsable', models.CharField(blank=True, choices=[('', 'Sélectionnez un responsable'), ('RESPONSABLE 0', 'Responsable 0'), ('RESPONSABLE 1', 'Responsable 1'), ('RESPONSABLE 2', 'Responsable 2'), ('RESPONSABLE 3', 'Responsable 3'), ('RESPONSABLE RAPHIA', 'Responsable Raphia')], max_length=100, null=True)),
                ('nouvelle_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('nouvelle_categorie', models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], max_length=10, null=True)),
                ('nouvelle_section', models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BRODERIE MACHINE', 'BRODERIE MACHINE'), ('BRODERIE MAIN AK17', 'BRODERIE MAIN AK17'), ('BRODERIE MAIN DEV', 'BRODERIE MAIN DEV'), ('BUREAU DE METHODE', 'BUREAU DE METHODE'), ('CONTROLE QUALITE AS', 'CONTROLE QUALITE AS'), ('CHAINE 1', 'CHAINE 1'), ('CHAINE 2', 'CHAINE 2'), ('CHAINE 3', 'CHAINE 3'), ('CHAINE 4', 'CHAINE 4'), ('CHAINE 5', 'CHAINE 5'), ('CHAINE 6', 'CHAINE 6'), ('CHAINE 7', 'CHAINE 7'), ('CHAINE 8', 'CHAINE 8'), ('CHAINE 9', 'CHAINE 9'), ('CHAINE 10', 'CHAINE 10'), ('CHAINE 11', 'CHAINE 11'), ('CHAINE 12', 'CHAINE 12'), ('CHAINE CUIR', 'CHAINE CUIR'), ('COLLECTION', 'COLLECTION'), ('COUPE', 'COUPE'), ('COUPE COLLECTION', 'COUPE COLLECTION'), ('FINITION D', 'FINITION D'), ('FINITION M', 'FINITION M'), ('FINITION P', 'FINITION P'), ('FINITION Q', 'FINITION Q'), ('FINITION R', 'FINITION R'), ('LECTRA', 'LECTRA'), ('LEMARIE HVA', 'LEMARIE HVA'), ('MAINTENANCE', 'MAINTENANCE'), ('MAISON', 'MAISON'), ('PACKING/EXPEDITION', 'PACKING/EXPEDITION'), ('PLISSE', 'PLISSE'), ('POLE QUALITE 1', 'POLE QUALITE 1'), ('POLE QUALITE 2', 'POLE QUALITE 2'), ('RAPHIA 1', 'RAPHIA 1'), ('RAPHIA 2', 'RAPHIA 2'), ('RAPHIA 3', 'RAPHIA 3'), ('RAPHIA 4', 'RAPHIA 4'), ('RAPHIA 5', 'RAPHIA 5'), ('RAPHIA 6', 'RAPHIA 6'), ('RESPONSABLE 0', 'RESPONSABLE 0'), ('RESPONSABLE 1', 'RESPONSABLE 1'), ('RESPONSABLE 2', 'RESPONSABLE 2'), ('RESPONSABLE 3', 'RESPONSABLE 3'), ('RESPONSABLE RAPHIA', 'RESPONSABLE RAPHIA'), ('SECURITE', 'SECURITE')], max_length=50, null=True)),
                ('nouveau_responsable', models.CharField(blank=True, choices=[('', 'Sélectionnez un responsable'), ('RESPONSABLE 0', 'Responsable 0'), ('RESPONSABLE 1', 'Responsable 1'), ('RESPONSABLE 2', 'Responsable 2'), ('RESPONSABLE 3', 'Responsable 3'), ('RESPONSABLE RAPHIA', 'Responsable Raphia')], max_length=100, null=True)),
                ('nouveau_salaire_base', models.DecimalField(blank=True, decimal_places=2, help_text='Nouveau salaire de base (optionnel)', max_digits=12, null=True)),
                ('motif', models.TextField(help_text="Raison de l'évolution de poste")),
                ('document_reference', models.FileField(blank=True, null=True, upload_to='evolutions_poste/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('EFFECTUEE', 'Effectuée')], default='PROPOSEE', max_length=20)),
                ('commentaire_validation', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions_poste', to='personnel.informationpersonnelle')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évolution de poste',
                'verbose_name_plural': 'Évolutions de poste',
                'ordering': ['-date_effet', '-created_at'],
            },
        ),
    ]
