# Generated by Django 5.2.7 on 2025-12-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0033_evolutionposte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvolutionPoste',
        ),
    ]
