# Generated by Django 5.2.7 on 2025-12-10 05:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0034_delete_evolutionposte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_evolution', models.CharField(choices=[('PROMOTION', 'Promotion'), ('MUTATION', 'Mutation'), ('CHANGEMENT_FONCTION', 'Changement de fonction'), ('CHANGEMENT_SECTION', 'Changement de section'), ('CHANGEMENT_RESPONSABLE', 'Changement de responsable'), ('CHANGEMENT_CATEGORIE', 'Changement de catégorie'), ('AUTRE', 'Autre')], max_length=50, verbose_name="Type d'évolution")),
                ('statut', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('EFFECTUEE', 'Effectuée')], default='PROPOSEE', max_length=20, verbose_name='Statut')),
                ('date_effet', models.DateField(help_text="Date à laquelle l'évolution prend effet", verbose_name="Date d'effet")),
                ('ancienne_categorie', models.CharField(blank=True, max_length=10, null=True)),
                ('ancienne_section', models.CharField(blank=True, max_length=50, null=True)),
                ('ancienne_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('ancien_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('nouvelle_categorie', models.CharField(blank=True, max_length=10, null=True)),
                ('nouvelle_section', models.CharField(blank=True, max_length=50, null=True)),
                ('nouvelle_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('nouveau_responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('motif', models.TextField(blank=True, help_text="Motif de l'évolution", null=True)),
                ('commentaire', models.TextField(blank=True, help_text='Commentaires supplémentaires', null=True)),
                ('document_reference', models.FileField(blank=True, null=True, upload_to='evolutions_poste/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Document de référence')),
                ('date_approbation', models.DateField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('date_effet_reelle', models.DateField(blank=True, null=True, verbose_name="Date d'effet réelle")),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_approuvees', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions_poste', to='personnel.informationpersonnelle')),
                ('initie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_initiees', to=settings.AUTH_USER_MODEL, verbose_name='Initié par')),
            ],
            options={
                'verbose_name': 'Évolution de poste',
                'verbose_name_plural': 'Évolutions de poste',
                'ordering': ['-date_effet', '-created_at'],
            },
        ),
    ]
