# Generated by Django 5.2.7 on 2025-12-10 11:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0035_evolutionposte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evolutionposte',
            options={'ordering': ['-created_at'], 'verbose_name': 'Évolution de poste', 'verbose_name_plural': 'Évolutions de poste'},
        ),
        migrations.RemoveField(
            model_name='evolutionposte',
            name='approuve_par',
        ),
        migrations.RemoveField(
            model_name='evolutionposte',
            name='date_approbation',
        ),
        migrations.RemoveField(
            model_name='evolutionposte',
            name='date_effet_reelle',
        ),
        migrations.RemoveField(
            model_name='evolutionposte',
            name='document_reference',
        ),
        migrations.RemoveField(
            model_name='evolutionposte',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='evolutionposte',
            name='type_evolution',
        ),
        migrations.AddField(
            model_name='evolutionposte',
            name='appliquee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evolutionposte',
            name='appliquee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_appliquees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evolutionposte',
            name='date_application',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evolutionposte',
            name='description_motif',
            field=models.TextField(blank=True, help_text='Détails du motif', null=True),
        ),
        migrations.AddField(
            model_name='evolutionposte',
            name='document_justificatif',
            field=models.FileField(blank=True, null=True, upload_to='evolutions_poste/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='date_effet',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='initie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_initiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='motif',
            field=models.CharField(blank=True, choices=[('PROMOTION', 'Promotion'), ('CHANGEMENT_SECTION', 'Changement de section'), ('CHANGEMENT_FONCTION', 'Changement de fonction'), ('CHANGEMENT_CATEGORIE', 'Changement de catégorie'), ('CHANGEMENT_RESPONSABLE', 'Changement de responsable'), ('AUTRE', 'Autre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='nouveau_responsable',
            field=models.CharField(blank=True, choices=[('', 'Sélectionnez un responsable'), ('RESPONSABLE 0', 'Responsable 0'), ('RESPONSABLE 1', 'Responsable 1'), ('RESPONSABLE 2', 'Responsable 2'), ('RESPONSABLE 3', 'Responsable 3'), ('RESPONSABLE RAPHIA', 'Responsable Raphia')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='nouvelle_categorie',
            field=models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='nouvelle_section',
            field=models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BRODERIE MACHINE', 'BRODERIE MACHINE'), ('BRODERIE MAIN AK17', 'BRODERIE MAIN AK17'), ('BRODERIE MAIN DEV', 'BRODERIE MAIN DEV'), ('BUREAU DE METHODE', 'BUREAU DE METHODE'), ('CONTROLE QUALITE AS', 'CONTROLE QUALITE AS'), ('CHAINE 1', 'CHAINE 1'), ('CHAINE 2', 'CHAINE 2'), ('CHAINE 3', 'CHAINE 3'), ('CHAINE 4', 'CHAINE 4'), ('CHAINE 5', 'CHAINE 5'), ('CHAINE 6', 'CHAINE 6'), ('CHAINE 7', 'CHAINE 7'), ('CHAINE 8', 'CHAINE 8'), ('CHAINE 9', 'CHAINE 9'), ('CHAINE 10', 'CHAINE 10'), ('CHAINE 11', 'CHAINE 11'), ('CHAINE 12', 'CHAINE 12'), ('CHAINE CUIR', 'CHAINE CUIR'), ('COLLECTION', 'COLLECTION'), ('COUPE', 'COUPE'), ('COUPE COLLECTION', 'COUPE COLLECTION'), ('FINITION D', 'FINITION D'), ('FINITION M', 'FINITION M'), ('FINITION P', 'FINITION P'), ('FINITION Q', 'FINITION Q'), ('FINITION R', 'FINITION R'), ('LECTRA', 'LECTRA'), ('LEMARIE HVA', 'LEMARIE HVA'), ('MAINTENANCE', 'MAINTENANCE'), ('MAISON', 'MAISON'), ('PACKING/EXPEDITION', 'PACKING/EXPEDITION'), ('PLISSE', 'PLISSE'), ('POLE QUALITE 1', 'POLE QUALITE 1'), ('POLE QUALITE 2', 'POLE QUALITE 2'), ('RAPHIA 1', 'RAPHIA 1'), ('RAPHIA 2', 'RAPHIA 2'), ('RAPHIA 3', 'RAPHIA 3'), ('RAPHIA 4', 'RAPHIA 4'), ('RAPHIA 5', 'RAPHIA 5'), ('RAPHIA 6', 'RAPHIA 6'), ('RESPONSABLE 0', 'RESPONSABLE 0'), ('RESPONSABLE 1', 'RESPONSABLE 1'), ('RESPONSABLE 2', 'RESPONSABLE 2'), ('RESPONSABLE 3', 'RESPONSABLE 3'), ('RESPONSABLE RAPHIA', 'RESPONSABLE RAPHIA'), ('SECURITE', 'SECURITE')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='HistoriqueEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_evolutions', to='personnel.informationpersonnelle')),
                ('evolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='personnel.evolutionposte')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
