# Generated by Django 5.2.7 on 2025-12-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0036_alter_evolutionposte_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiqueevolution',
            name='evolution',
        ),
        migrations.RemoveField(
            model_name='historiqueevolution',
            name='effectue_par',
        ),
        migrations.RemoveField(
            model_name='historiqueevolution',
            name='employe',
        ),
        migrations.DeleteModel(
            name='EvolutionPoste',
        ),
        migrations.DeleteModel(
            name='HistoriqueEvolution',
        ),
    ]
