# Generated by Django 5.2.7 on 2025-12-11 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0037_remove_historiqueevolution_evolution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ancienne_categorie', models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], max_length=10, null=True)),
                ('ancienne_fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('ancienne_section', models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BRODERIE MACHINE', 'BRODERIE MACHINE'), ('BRODERIE MAIN AK17', 'BRODERIE MAIN AK17'), ('BRODERIE MAIN DEV', 'BRODERIE MAIN DEV'), ('BUREAU DE METHODE', 'BUREAU DE METHODE'), ('CONTROLE QUALITE AS', 'CONTROLE QUALITE AS'), ('CHAINE 1', 'CHAINE 1'), ('CHAINE 2', 'CHAINE 2'), ('CHAINE 3', 'CHAINE 3'), ('CHAINE 4', 'CHAINE 4'), ('CHAINE 5', 'CHAINE 5'), ('CHAINE 6', 'CHAINE 6'), ('CHAINE 7', 'CHAINE 7'), ('CHAINE 8', 'CHAINE 8'), ('CHAINE 9', 'CHAINE 9'), ('CHAINE 10', 'CHAINE 10'), ('CHAINE 11', 'CHAINE 11'), ('CHAINE 12', 'CHAINE 12'), ('CHAINE CUIR', 'CHAINE CUIR'), ('COLLECTION', 'COLLECTION'), ('COUPE', 'COUPE'), ('COUPE COLLECTION', 'COUPE COLLECTION'), ('FINITION D', 'FINITION D'), ('FINITION M', 'FINITION M'), ('FINITION P', 'FINITION P'), ('FINITION Q', 'FINITION Q'), ('FINITION R', 'FINITION R'), ('LECTRA', 'LECTRA'), ('LEMARIE HVA', 'LEMARIE HVA'), ('MAINTENANCE', 'MAINTENANCE'), ('MAISON', 'MAISON'), ('PACKING/EXPEDITION', 'PACKING/EXPEDITION'), ('PLISSE', 'PLISSE'), ('POLE QUALITE 1', 'POLE QUALITE 1'), ('POLE QUALITE 2', 'POLE QUALITE 2'), ('RAPHIA 1', 'RAPHIA 1'), ('RAPHIA 2', 'RAPHIA 2'), ('RAPHIA 3', 'RAPHIA 3'), ('RAPHIA 4', 'RAPHIA 4'), ('RAPHIA 5', 'RAPHIA 5'), ('RAPHIA 6', 'RAPHIA 6'), ('RESPONSABLE 0', 'RESPONSABLE 0'), ('RESPONSABLE 1', 'RESPONSABLE 1'), ('RESPONSABLE 2', 'RESPONSABLE 2'), ('RESPONSABLE 3', 'RESPONSABLE 3'), ('RESPONSABLE RAPHIA', 'RESPONSABLE RAPHIA'), ('SECURITE', 'SECURITE')], max_length=50, null=True)),
                ('ancien_responsable', models.CharField(blank=True, choices=[('', 'Sélectionnez un responsable'), ('RESPONSABLE 0', 'Responsable 0'), ('RESPONSABLE 1', 'Responsable 1'), ('RESPONSABLE 2', 'Responsable 2'), ('RESPONSABLE 3', 'Responsable 3'), ('RESPONSABLE RAPHIA', 'Responsable Raphia')], max_length=100, null=True)),
                ('nouvelle_categorie', models.CharField(choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], max_length=10)),
                ('nouvelle_fonction', models.CharField(max_length=100)),
                ('nouvelle_section', models.CharField(choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BRODERIE MACHINE', 'BRODERIE MACHINE'), ('BRODERIE MAIN AK17', 'BRODERIE MAIN AK17'), ('BRODERIE MAIN DEV', 'BRODERIE MAIN DEV'), ('BUREAU DE METHODE', 'BUREAU DE METHODE'), ('CONTROLE QUALITE AS', 'CONTROLE QUALITE AS'), ('CHAINE 1', 'CHAINE 1'), ('CHAINE 2', 'CHAINE 2'), ('CHAINE 3', 'CHAINE 3'), ('CHAINE 4', 'CHAINE 4'), ('CHAINE 5', 'CHAINE 5'), ('CHAINE 6', 'CHAINE 6'), ('CHAINE 7', 'CHAINE 7'), ('CHAINE 8', 'CHAINE 8'), ('CHAINE 9', 'CHAINE 9'), ('CHAINE 10', 'CHAINE 10'), ('CHAINE 11', 'CHAINE 11'), ('CHAINE 12', 'CHAINE 12'), ('CHAINE CUIR', 'CHAINE CUIR'), ('COLLECTION', 'COLLECTION'), ('COUPE', 'COUPE'), ('COUPE COLLECTION', 'COUPE COLLECTION'), ('FINITION D', 'FINITION D'), ('FINITION M', 'FINITION M'), ('FINITION P', 'FINITION P'), ('FINITION Q', 'FINITION Q'), ('FINITION R', 'FINITION R'), ('LECTRA', 'LECTRA'), ('LEMARIE HVA', 'LEMARIE HVA'), ('MAINTENANCE', 'MAINTENANCE'), ('MAISON', 'MAISON'), ('PACKING/EXPEDITION', 'PACKING/EXPEDITION'), ('PLISSE', 'PLISSE'), ('POLE QUALITE 1', 'POLE QUALITE 1'), ('POLE QUALITE 2', 'POLE QUALITE 2'), ('RAPHIA 1', 'RAPHIA 1'), ('RAPHIA 2', 'RAPHIA 2'), ('RAPHIA 3', 'RAPHIA 3'), ('RAPHIA 4', 'RAPHIA 4'), ('RAPHIA 5', 'RAPHIA 5'), ('RAPHIA 6', 'RAPHIA 6'), ('RESPONSABLE 0', 'RESPONSABLE 0'), ('RESPONSABLE 1', 'RESPONSABLE 1'), ('RESPONSABLE 2', 'RESPONSABLE 2'), ('RESPONSABLE 3', 'RESPONSABLE 3'), ('RESPONSABLE RAPHIA', 'RESPONSABLE RAPHIA'), ('SECURITE', 'SECURITE')], max_length=50)),
                ('nouveau_responsable', models.CharField(blank=True, choices=[('', 'Sélectionnez un responsable'), ('RESPONSABLE 0', 'Responsable 0'), ('RESPONSABLE 1', 'Responsable 1'), ('RESPONSABLE 2', 'Responsable 2'), ('RESPONSABLE 3', 'Responsable 3'), ('RESPONSABLE RAPHIA', 'Responsable Raphia')], max_length=100, null=True)),
                ('date_evolution', models.DateField(help_text="Date effective de l'évolution de poste")),
                ('motif', models.TextField(help_text='Motif ou raison du changement de poste')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('APPROUVEE', 'Approuvée'), ('REALISEE', 'Réalisée'), ('ANNULEE', 'Annulée')], default='PROPOSEE', max_length=20)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions_poste', to='personnel.informationpersonnelle')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_poste_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évolution de poste',
                'verbose_name_plural': 'Évolutions de poste',
                'ordering': ['-date_evolution', '-created_at'],
            },
        ),
    ]
