# Generated by Django 5.2.7 on 2026-01-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0038_evolutionposte'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BRODERIE MACHINE', 'BRODERIE MACHINE'), ('BRODERIE MAIN AK17', 'BRODERIE MAIN AK17'), ('BRODERIE MAIN DEV', 'BRODERIE MAIN DEV'), ('BUREAU DE METHODE', 'BUREAU DE METHODE'), ('CONTROLE QUALITE AS', 'CONTROLE QUALITE AS'), ('CHAINE 1', 'CHAINE 1'), ('CHAINE 2', 'CHAINE 2'), ('CHAINE 3', 'CHAINE 3'), ('CHAINE 4', 'CHAINE 4'), ('CHAINE 5', 'CHAINE 5'), ('CHAINE 6', 'CHAINE 6'), ('CHAINE 7', 'CHAINE 7'), ('CHAINE 8', 'CHAINE 8'), ('CHAINE 9', 'CHAINE 9'), ('CHAINE 10', 'CHAINE 10'), ('CHAINE 11', 'CHAINE 11'), ('CHAINE 12', 'CHAINE 12'), ('CHAINE CUIR', 'CHAINE CUIR'), ('COLLECTION', 'COLLECTION'), ('COUPE', 'COUPE'), ('COUPE COLLECTION', 'COUPE COLLECTION'), ('FINITION D', 'FINITION D'), ('FINITION M', 'FINITION M'), ('FINITION P', 'FINITION P'), ('FINITION Q', 'FINITION Q'), ('FINITION R', 'FINITION R'), ('LECTRA', 'LECTRA'), ('LEMARIE HVA', 'LEMARIE HVA'), ('MAINTENANCE', 'MAINTENANCE'), ('MAISON', 'MAISON'), ('PACKING/EXPEDITION', 'PACKING/EXPEDITION'), ('PLISSE', 'PLISSE'), ('POLE QUALITE 1', 'POLE QUALITE 1'), ('POLE QUALITE 2', 'POLE QUALITE 2'), ('RAPHIA 1', 'RAPHIA 1'), ('RAPHIA 2', 'RAPHIA 2'), ('RAPHIA 3', 'RAPHIA 3'), ('RAPHIA 4', 'RAPHIA 4'), ('RAPHIA 5', 'RAPHIA 5'), ('RAPHIA 6', 'RAPHIA 6'), ('RESPONSABLE 0', 'RESPONSABLE 0'), ('RESPONSABLE 1', 'RESPONSABLE 1'), ('RESPONSABLE 2', 'RESPONSABLE 2'), ('RESPONSABLE 3', 'RESPONSABLE 3'), ('RESPONSABLE RAPHIA', 'RESPONSABLE RAPHIA'), ('SECURITE', 'SECURITE')], max_length=50, unique=True, verbose_name='Section')),
                ('heure_entree', models.DecimalField(decimal_places=2, default=7.5, max_digits=4, verbose_name="Heure d'entrée (décimal)")),
                ('heure_sortie', models.DecimalField(decimal_places=2, default=17.5, max_digits=4, verbose_name='Heure de sortie (décimal)')),
                ('sortie_samedi', models.DecimalField(decimal_places=2, default=15.5, max_digits=4, verbose_name='Heure sortie samedi (décimal)')),
                ('heure_entree_format', models.TimeField(blank=True, null=True, verbose_name="Heure d'entrée (HH:MM)")),
                ('heure_sortie_format', models.TimeField(blank=True, null=True, verbose_name='Heure de sortie (HH:MM)')),
                ('sortie_samedi_format', models.TimeField(blank=True, null=True, verbose_name='Heure sortie samedi (HH:MM)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horaire Section',
                'verbose_name_plural': 'Horaires Sections',
                'ordering': ['section'],
            },
        ),
    ]
