# Generated by Django 5.2.7 on 2026-01-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0039_horairesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HoraireSection',
        ),
    ]
