# Generated by Django 5.2.7 on 2026-02-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0040_delete_horairesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='nom_complet',
            field=models.CharField(max_length=255),
        ),
    ]
