# Generated by Django 5.2.7 on 2026-03-04 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0041_alter_informationpersonnelle_nom_complet'),
    ]

    operations = [
        migrations.CreateModel(
            name='dboSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'dbo_section',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='code_pays_passport',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Code pays'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_a',
            field=models.DateField(blank=True, null=True, verbose_name='Permis Catégorie A'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_b',
            field=models.DateField(blank=True, null=True, verbose_name='Permis Catégorie B'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_c',
            field=models.DateField(blank=True, null=True, verbose_name='Permis Catégorie C'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_d',
            field=models.DateField(blank=True, null=True, verbose_name='Permis Catégorie D'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_e',
            field=models.DateField(blank=True, null=True, verbose_name='Permis Catégorie E'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_f',
            field=models.DateField(blank=True, null=True, verbose_name='Permis Catégorie F'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='photo_hauteur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='photo_largeur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='photo_taille',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='photo_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='photo_validee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='type_passport',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Type de passport'),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='categorie',
            field=models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='fonction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='numero_cnaps',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='numero_ostie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='responsable_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evolutionposte',
            name='ancienne_responsable_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evol_ancienne_responsable_section', to='personnel.dbosection'),
        ),
        migrations.AddField(
            model_name='evolutionposte',
            name='nouvelle_responsable_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evol_nouvelle_responsable_section', to='personnel.dbosection'),
        ),
        migrations.AddField(
            model_name='informationprofessionnelle',
            name='responsable_section_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infos_pro_responsable_section_fk', to='personnel.dbosection'),
        ),
        migrations.AddField(
            model_name='informationprofessionnelle',
            name='section_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='infos_pro_section_fk', to='personnel.dbosection'),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='ancienne_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evol_ancienne_section', to='personnel.dbosection'),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='nouvelle_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evol_nouvelle_section', to='personnel.dbosection'),
        ),
    ]
