# Generated by Django 5.2.7 on 2026-03-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0042_dbosection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolutionposte',
            name='nouvelle_responsable_section',
        ),
        migrations.RemoveField(
            model_name='informationprofessionnelle',
            name='responsable_section_fk',
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='ancienne_section',
            field=models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BRODERIE MACHINE', 'BRODERIE MACHINE'), ('BRODERIE MAIN AK17', 'BRODERIE MAIN AK17'), ('BRODERIE MAIN DEV', 'BRODERIE MAIN DEV'), ('BUREAU DE METHODE', 'BUREAU DE METHODE'), ('CONTROLE QUALITE AS', 'CONTROLE QUALITE AS'), ('CHAINE 1', 'CHAINE 1'), ('CHAINE 2', 'CHAINE 2'), ('CHAINE 3', 'CHAINE 3'), ('CHAINE 4', 'CHAINE 4'), ('CHAINE 5', 'CHAINE 5'), ('CHAINE 6', 'CHAINE 6'), ('CHAINE 7', 'CHAINE 7'), ('CHAINE 8', 'CHAINE 8'), ('CHAINE 9', 'CHAINE 9'), ('CHAINE 10', 'CHAINE 10'), ('CHAINE 11', 'CHAINE 11'), ('CHAINE 12', 'CHAINE 12'), ('CHAINE CUIR', 'CHAINE CUIR'), ('COLLECTION', 'COLLECTION'), ('COUPE', 'COUPE'), ('COUPE COLLECTION', 'COUPE COLLECTION'), ('FINITION D', 'FINITION D'), ('FINITION M', 'FINITION M'), ('FINITION P', 'FINITION P'), ('FINITION Q', 'FINITION Q'), ('FINITION R', 'FINITION R'), ('LECTRA', 'LECTRA'), ('LEMARIE HVA', 'LEMARIE HVA'), ('MAINTENANCE', 'MAINTENANCE'), ('MAISON', 'MAISON'), ('PACKING/EXPEDITION', 'PACKING/EXPEDITION'), ('PLISSE', 'PLISSE'), ('POLE QUALITE 1', 'POLE QUALITE 1'), ('POLE QUALITE 2', 'POLE QUALITE 2'), ('RAPHIA 1', 'RAPHIA 1'), ('RAPHIA 2', 'RAPHIA 2'), ('RAPHIA 3', 'RAPHIA 3'), ('RAPHIA 4', 'RAPHIA 4'), ('RAPHIA 5', 'RAPHIA 5'), ('RAPHIA 6', 'RAPHIA 6'), ('RESPONSABLE 0', 'RESPONSABLE 0'), ('RESPONSABLE 1', 'RESPONSABLE 1'), ('RESPONSABLE 2', 'RESPONSABLE 2'), ('RESPONSABLE 3', 'RESPONSABLE 3'), ('RESPONSABLE RAPHIA', 'RESPONSABLE RAPHIA'), ('SECURITE', 'SECURITE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='nouvelle_section',
            field=models.CharField(choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BRODERIE MACHINE', 'BRODERIE MACHINE'), ('BRODERIE MAIN AK17', 'BRODERIE MAIN AK17'), ('BRODERIE MAIN DEV', 'BRODERIE MAIN DEV'), ('BUREAU DE METHODE', 'BUREAU DE METHODE'), ('CONTROLE QUALITE AS', 'CONTROLE QUALITE AS'), ('CHAINE 1', 'CHAINE 1'), ('CHAINE 2', 'CHAINE 2'), ('CHAINE 3', 'CHAINE 3'), ('CHAINE 4', 'CHAINE 4'), ('CHAINE 5', 'CHAINE 5'), ('CHAINE 6', 'CHAINE 6'), ('CHAINE 7', 'CHAINE 7'), ('CHAINE 8', 'CHAINE 8'), ('CHAINE 9', 'CHAINE 9'), ('CHAINE 10', 'CHAINE 10'), ('CHAINE 11', 'CHAINE 11'), ('CHAINE 12', 'CHAINE 12'), ('CHAINE CUIR', 'CHAINE CUIR'), ('COLLECTION', 'COLLECTION'), ('COUPE', 'COUPE'), ('COUPE COLLECTION', 'COUPE COLLECTION'), ('FINITION D', 'FINITION D'), ('FINITION M', 'FINITION M'), ('FINITION P', 'FINITION P'), ('FINITION Q', 'FINITION Q'), ('FINITION R', 'FINITION R'), ('LECTRA', 'LECTRA'), ('LEMARIE HVA', 'LEMARIE HVA'), ('MAINTENANCE', 'MAINTENANCE'), ('MAISON', 'MAISON'), ('PACKING/EXPEDITION', 'PACKING/EXPEDITION'), ('PLISSE', 'PLISSE'), ('POLE QUALITE 1', 'POLE QUALITE 1'), ('POLE QUALITE 2', 'POLE QUALITE 2'), ('RAPHIA 1', 'RAPHIA 1'), ('RAPHIA 2', 'RAPHIA 2'), ('RAPHIA 3', 'RAPHIA 3'), ('RAPHIA 4', 'RAPHIA 4'), ('RAPHIA 5', 'RAPHIA 5'), ('RAPHIA 6', 'RAPHIA 6'), ('RESPONSABLE 0', 'RESPONSABLE 0'), ('RESPONSABLE 1', 'RESPONSABLE 1'), ('RESPONSABLE 2', 'RESPONSABLE 2'), ('RESPONSABLE 3', 'RESPONSABLE 3'), ('RESPONSABLE RAPHIA', 'RESPONSABLE RAPHIA'), ('SECURITE', 'SECURITE')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='evolutionposte',
            name='ancienne_responsable_section',
        ),
        migrations.RemoveField(
            model_name='informationprofessionnelle',
            name='section_fk',
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='code_pays_passport',
            field=models.CharField(blank=True, help_text='Code pays du passport (ex: MDG, FRA)', max_length=3, null=True, verbose_name='Code pays'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_a',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis A", null=True, verbose_name='Permis Catégorie A'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_b',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis B", null=True, verbose_name='Permis Catégorie B'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_c',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis C", null=True, verbose_name='Permis Catégorie C'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_d',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis D", null=True, verbose_name='Permis Catégorie D'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_e',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis E", null=True, verbose_name='Permis Catégorie E'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='permis_categorie_f',
            field=models.DateField(blank=True, help_text="Date d'obtention du permis F", null=True, verbose_name='Permis Catégorie F'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='photo_hauteur',
            field=models.PositiveIntegerField(blank=True, help_text='Hauteur en pixels', null=True),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='photo_largeur',
            field=models.PositiveIntegerField(blank=True, help_text='Largeur en pixels', null=True),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='photo_taille',
            field=models.PositiveIntegerField(blank=True, help_text='Taille du fichier en octets', null=True),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='photo_type',
            field=models.CharField(blank=True, help_text='Extension du fichier', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='photo_validee',
            field=models.BooleanField(default=False, help_text='Statut de validation de la photo'),
        ),
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='type_passport',
            field=models.CharField(blank=True, help_text='Type de passport (ex: Ordinaire, Diplomatique)', max_length=20, null=True, verbose_name='Type de passport'),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='categorie',
            field=models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('0S1', '0S1'), ('0S2', '0S2'), ('0S3', '0S3'), ('0P1A', '0P1A'), ('0P1B', '0P1B'), ('0P2A', '0P2A'), ('0P2B', '0P2B'), ('0P3', '0P3'), ('H.C', 'H.C')], help_text="Catégorie professionnelle de l'employé", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='date_embauche',
            field=models.DateField(blank=True, help_text="Date d'embauche de l'employé", null=True),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='fonction',
            field=models.CharField(blank=True, help_text='Fonction ou poste occupé', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='numero_cnaps',
            field=models.CharField(blank=True, help_text='Numéro CNAPS (Caisse Nationale de Prévoyance Sociale)', max_length=50, null=True, verbose_name='Numéro CNAPS'),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='numero_ostie',
            field=models.CharField(blank=True, help_text='Numéro OSTIE (Organisme de Santé et de Travail pour les Indépendants et Employés)', max_length=50, null=True, verbose_name='Numéro OSTIE'),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='responsable_section',
            field=models.CharField(blank=True, help_text='Nom du responsable de la section', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='section',
            field=models.CharField(blank=True, choices=[('ADMINISTRATION', 'ADMINISTRATION'), ('BRODERIE MACHINE', 'BRODERIE MACHINE'), ('BRODERIE MAIN AK17', 'BRODERIE MAIN AK17'), ('BRODERIE MAIN DEV', 'BRODERIE MAIN DEV'), ('BUREAU DE METHODE', 'BUREAU DE METHODE'), ('CONTROLE QUALITE AS', 'CONTROLE QUALITE AS'), ('CHAINE 1', 'CHAINE 1'), ('CHAINE 2', 'CHAINE 2'), ('CHAINE 3', 'CHAINE 3'), ('CHAINE 4', 'CHAINE 4'), ('CHAINE 5', 'CHAINE 5'), ('CHAINE 6', 'CHAINE 6'), ('CHAINE 7', 'CHAINE 7'), ('CHAINE 8', 'CHAINE 8'), ('CHAINE 9', 'CHAINE 9'), ('CHAINE 10', 'CHAINE 10'), ('CHAINE 11', 'CHAINE 11'), ('CHAINE 12', 'CHAINE 12'), ('CHAINE CUIR', 'CHAINE CUIR'), ('COLLECTION', 'COLLECTION'), ('COUPE', 'COUPE'), ('COUPE COLLECTION', 'COUPE COLLECTION'), ('FINITION D', 'FINITION D'), ('FINITION M', 'FINITION M'), ('FINITION P', 'FINITION P'), ('FINITION Q', 'FINITION Q'), ('FINITION R', 'FINITION R'), ('LECTRA', 'LECTRA'), ('LEMARIE HVA', 'LEMARIE HVA'), ('MAINTENANCE', 'MAINTENANCE'), ('MAISON', 'MAISON'), ('PACKING/EXPEDITION', 'PACKING/EXPEDITION'), ('PLISSE', 'PLISSE'), ('POLE QUALITE 1', 'POLE QUALITE 1'), ('POLE QUALITE 2', 'POLE QUALITE 2'), ('RAPHIA 1', 'RAPHIA 1'), ('RAPHIA 2', 'RAPHIA 2'), ('RAPHIA 3', 'RAPHIA 3'), ('RAPHIA 4', 'RAPHIA 4'), ('RAPHIA 5', 'RAPHIA 5'), ('RAPHIA 6', 'RAPHIA 6'), ('RESPONSABLE 0', 'RESPONSABLE 0'), ('RESPONSABLE 1', 'RESPONSABLE 1'), ('RESPONSABLE 2', 'RESPONSABLE 2'), ('RESPONSABLE 3', 'RESPONSABLE 3'), ('RESPONSABLE RAPHIA', 'RESPONSABLE RAPHIA'), ('SECURITE', 'SECURITE')], help_text="Section/département de l'employé", max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='dboSection',
        ),
    ]
