# Generated by Django 5.2.7 on 2026-03-04 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0043_remove_evolutionposte_nouvelle_responsable_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionposte',
            name='ancienne_section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='nouvelle_section',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='section',
            field=models.CharField(blank=True, help_text="Section/département de l'employé", max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DboSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_poste', models.CharField(blank=True, help_text="Valeur brute du champ 'section' dans InformationProfessionnelle", max_length=100)),
                ('responsable_section_saisie', models.CharField(blank=True, help_text="Valeur brute du champ 'responsable_section' dans InformationProfessionnelle", max_length=100)),
                ('section_reelle', models.CharField(blank=True, help_text='Section effective : responsable_section si renseigné, sinon section', max_length=100)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dbo_section', to='personnel.informationpersonnelle')),
            ],
            options={
                'verbose_name': 'Section employé',
                'verbose_name_plural': 'Sections employés',
                'db_table': 'dbo_section',
                'ordering': ['section_reelle', 'employe__nom_complet'],
            },
        ),
    ]
