# Generated by Django 5.2.7 on 2026-03-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0045_alter_evolutionposte_ancienne_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionposte',
            name='ancienne_section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evolutionposte',
            name='nouvelle_section',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='informationprofessionnelle',
            name='section',
            field=models.CharField(blank=True, help_text="Section/département de l'employé", max_length=50, null=True),
        ),
    ]
