# Generated by Django 5.2.7 on 2026-03-05 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0046_alter_evolutionposte_ancienne_section_and_more'),
        ('presence', '0041_section_usersection'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationprofessionnelle',
            name='section_ref',
            field=models.ForeignKey(blank=True, help_text='Section issue de db_section, calculée automatiquement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_pro', to='presence.section', verbose_name='Section (référence)'),
        ),
    ]
