# Generated by Django 5.2.7 on 2026-04-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0047_informationprofessionnelle_section_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpersonnelle',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin'), ('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ'), ('FÉMININ', 'FÉMININ')], max_length=10, null=True),
        ),
    ]
