# Generated by Django 5.2.7 on 2026-04-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0048_alter_informationpersonnelle_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpersonnelle',
            name='depart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
