# Generated by Django 5.2.14 on 2026-09-22 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0051_alter_informationpersonnelle_created_by'),
        ('presence', '0062_horairesection_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super administrateur'), ('ADMIN', 'Administrateur simple'), ('RESPONSABLE', 'Responsable de section')], default='ADMIN', max_length=20)),
                ('section', models.ForeignKey(blank=True, help_text='À remplir uniquement si role = RESPONSABLE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsables', to='presence.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
