# Generated by Django 5.2.14 on 2026-09-22 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0052_profilutilisateur'),
        ('presence', '0062_horairesection_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Renseigné uniquement si role = RESPONSABLE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsables', to='presence.section'),
        ),
    ]
