# Generated by Django 5.2.14 on 2026-09-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0053_alter_profilutilisateur_section'),
        ('presence', '0062_horairesection_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilutilisateur',
            name='section',
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Sections visibles par ce responsable (utilisé uniquement si role = RESPONSABLE)', related_name='responsables', to='presence.section'),
        ),
    ]
