# Generated by Django 5.2.7 on 2025-10-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('raison_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Raison sociale')),
                ('rcs', models.CharField(blank=True, max_length=20, null=True, verbose_name='RCS')),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF')),
                ('stat', models.CharField(blank=True, max_length=20, null=True, verbose_name='STAT')),
                ('ostie', models.CharField(blank=True, max_length=20, null=True)),
                ('cnaps', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAPS')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Société',
                'verbose_name_plural': 'Sociétés',
                'db_table': 'info_societe',
                'ordering': ['name'],
            },
        ),
    ]
