# # Generated by Django 5.2.7 on 2026-05-30 05:58

# import django.db.models.deletion
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Calendrier',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('titre', models.CharField(max_length=200, verbose_name='Titre du calendrier')),
#                 ('annee', models.IntegerField(verbose_name='Année')),
#                 ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
#                 ('cree_le', models.DateTimeField(auto_now_add=True)),
#                 ('modifie_le', models.DateTimeField(auto_now=True)),
#                 ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendriers_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
#             ],
#             options={
#                 'verbose_name': 'Calendrier',
#                 'verbose_name_plural': 'Calendriers',
#                 'db_table': 'calendrier',
#                 'ordering': ['-annee', 'titre'],
#                 'unique_together': {('titre', 'annee')},
#             },
#         ),
#         migrations.CreateModel(
#             name='JourFerie',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('titre', models.CharField(max_length=200, verbose_name='Titre / Nom du jour')),
#                 ('date', models.DateField(verbose_name='Date')),
#                 ('type_jour', models.CharField(choices=[('ferie_national', 'Férié national'), ('ferie_entreprise', 'Férié entreprise'), ('evenement', 'Événement'), ('fermeture', 'Fermeture'), ('autre', 'Autre')], default='ferie_national', max_length=30, verbose_name='Type')),
#                 ('couleur', models.CharField(choices=[('#ef4444', 'Rouge'), ('#f97316', 'Orange'), ('#eab308', 'Jaune'), ('#22c55e', 'Vert'), ('#3b82f6', 'Bleu'), ('#8b5cf6', 'Violet'), ('#ec4899', 'Rose'), ('#6b7280', 'Gris'), ('#56656b', 'Ardoise (AKJ)'), ('#0ea5e9', 'Cyan')], default='#ef4444', max_length=10, verbose_name='Couleur')),
#                 ('est_recurrent', models.BooleanField(default=False, help_text='Si coché, ce jour sera automatiquement considéré férié chaque année', verbose_name='Récurrent chaque année')),
#                 ('description', models.TextField(blank=True, null=True, verbose_name='Description / Note')),
#                 ('cree_le', models.DateTimeField(auto_now_add=True)),
#                 ('modifie_le', models.DateTimeField(auto_now=True)),
#                 ('calendrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours_feries', to='calendrier.calendrier', verbose_name='Calendrier')),
#                 ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jours_feries_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
#             ],
#             options={
#                 'verbose_name': 'Jour férié',
#                 'verbose_name_plural': 'Jours fériés',
#                 'db_table': 'calendrier_jour_ferie',
#                 'ordering': ['date'],
#             },
#         ),
#     ]


from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du calendrier')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='calendriers_crees',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Créé par'
                )),
            ],
            options={
                'verbose_name': 'Calendrier',
                'verbose_name_plural': 'Calendriers',
                'db_table': 'calendrier',
                'ordering': ['-annee', 'titre'],
                'unique_together': {('titre', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre / Nom du jour')),
                ('date', models.DateField(verbose_name='Date')),
                ('type_jour', models.CharField(
                    choices=[
                        ('ferie_national', 'Férié national'),
                        ('ferie_entreprise', 'Férié entreprise'),
                        ('evenement', 'Événement'),
                        ('fermeture', 'Fermeture'),
                        ('autre', 'Autre'),
                    ],
                    default='ferie_national',
                    max_length=30,
                    verbose_name='Type'
                )),
                ('couleur', models.CharField(
                    choices=[
                        ('#ef4444', 'Rouge'),
                        ('#f97316', 'Orange'),
                        ('#eab308', 'Jaune'),
                        ('#22c55e', 'Vert'),
                        ('#3b82f6', 'Bleu'),
                        ('#8b5cf6', 'Violet'),
                        ('#ec4899', 'Rose'),
                        ('#6b7280', 'Gris'),
                        ('#56656b', 'Ardoise (AKJ)'),
                        ('#0ea5e9', 'Cyan'),
                    ],
                    default='#ef4444',
                    max_length=10,
                    verbose_name='Couleur'
                )),
                ('est_recurrent', models.BooleanField(default=False, verbose_name='Récurrent chaque année')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Note')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('calendrier', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='jours_feries',
                    to='calendrier.calendrier',
                    verbose_name='Calendrier'
                )),
                ('cree_par', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='jours_feries_crees',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Créé par'
                )),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'db_table': 'calendrier_jour_ferie',
                'ordering': ['date'],
            },
        ),
    ]