# Generated by Django 5.2.7 on 2026-06-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jourferie',
            name='est_recurrent',
            field=models.BooleanField(default=False, help_text='Si coché, ce jour sera automatiquement considéré férié chaque année', verbose_name='Récurrent chaque année'),
        ),
    ]
