# Generated by Django 5.2.7 on 2025-12-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('numauto', models.AutoField(db_column='NumAuto', primary_key=True, serialize=False)),
                ('checktime', models.DateTimeField(db_column='checktime')),
                ('checktype', models.CharField(db_column='checktype', max_length=1)),
            ],
            options={
                'db_table': 'checkinout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.IntegerField(db_column='userid', primary_key=True, serialize=False)),
                ('badgenumber', models.CharField(db_column='Badgenumber', max_length=50)),
                ('ssn', models.CharField(blank=True, db_column='ssn', max_length=50, null=True)),
                ('name', models.CharField(db_column='Name', max_length=150)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(db_column='date', primary_key=True, serialize=False)),
                ('code_date', models.CharField(db_column='code_date', max_length=2)),
                ('mois_concerné', models.IntegerField(db_column='mois_concerne')),
                ('annee_concernée', models.IntegerField(db_column='annee_concernee')),
                ('est_hors_periode', models.BooleanField(db_column='est_hors_periode', default=False)),
            ],
            options={
                'db_table': 'date',
                'ordering': ['date'],
                'managed': True,
            },
        ),
    ]
