# Generated by Django 5.2.7 on 2025-12-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
