# Generated by Django 5.2.7 on 2025-12-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_delete_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date', unique=True)),
                ('code_date', models.CharField(db_column='code_date', max_length=2)),
                ('semaine_mois', models.IntegerField(db_column='semaine_mois')),
                ('jour_semaine', models.IntegerField(db_column='jour_semaine')),
                ('periode_presence', models.BooleanField(db_column='periode_presence', default=False)),
                ('evenement', models.CharField(db_column='evenement', default='F', max_length=1)),
            ],
            options={
                'db_table': 'date_presence',
                'managed': True,
            },
        ),
    ]
