# Generated by Django 5.2.7 on 2025-12-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0003_datepresence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatePresence',
        ),
    ]
