# Generated by Django 5.2.7 on 2025-12-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0004_delete_datepresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('code_date', models.CharField(max_length=2)),
                ('est_incluse', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'date_presence',
                'ordering': ['date'],
            },
        ),
    ]
