# Generated by Django 5.2.7 on 2025-12-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0005_datepresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('code_date', models.CharField(max_length=2)),
                ('mois_reference', models.DateField()),
            ],
            options={
                'db_table': 'date',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='DatePresence',
        ),
    ]
