# Generated by Django 5.2.7 on 2025-12-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0006_date_delete_datepresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='hors_periode',
            field=models.BooleanField(default=False),
        ),
    ]
