# Generated by Django 5.2.7 on 2026-01-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0008_horairesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HoraireSection',
        ),
    ]
