# Generated by Django 5.2.7 on 2026-01-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0009_delete_horairesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireSection',
            fields=[
                ('section', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('heure_entree', models.DecimalField(decimal_places=2, help_text="Heure d'entrée en format décimal (ex: 7.50 = 7h30)", max_digits=4)),
                ('heure_sortie', models.DecimalField(decimal_places=2, help_text='Heure de sortie en format décimal (ex: 17.83 = 17h50)', max_digits=4)),
                ('sortie_samedi', models.DecimalField(decimal_places=2, help_text='Heure de sortie le samedi en format décimal', max_digits=4)),
            ],
            options={
                'verbose_name': 'Horaire de section',
                'verbose_name_plural': 'Horaires de section',
                'db_table': 'horaire_section',
                'ordering': ['section'],
            },
        ),
    ]
