# Generated by Django 5.2.7 on 2026-01-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0010_horairesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='userid')),
                ('date', models.DateField()),
                ('type_evenement', models.CharField(choices=[('X', 'Travail normal'), ('RM', 'Repos Médical'), ('HP', 'Hospitalisation'), ('RC', 'Repos de convalescence'), ('ANO', 'Absence Non Autorisée'), ('CP', 'Congé Payé'), ('EF', 'Événement familial'), ('F', 'Fonction (délégués)'), ('PS', 'Permission Spéciale'), ('A', 'Absent')], default='X', max_length=3)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'evenement',
                'ordering': ['date', 'userid'],
                'unique_together': {('userid', 'date')},
            },
        ),
    ]
