# Generated by Django 5.2.7 on 2026-01-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0011_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='heure_entree_comptabilisee',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='heure_entree_reelle',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='heure_sortie_comptabilisee',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='heure_sortie_reelle',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
