# Generated by Django 5.2.7 on 2026-01-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0012_evenement_heure_entree_comptabilisee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='heure_entree_comptabilisee',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='heure_entree_reelle',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='heure_sortie_comptabilisee',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='heure_sortie_reelle',
        ),
    ]
