# Generated by Django 5.2.7 on 2026-01-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0013_remove_evenement_heure_entree_comptabilisee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificationHeure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='userid')),
                ('date', models.DateField()),
                ('type_modification', models.CharField(choices=[('ENTREE', "Modification heure d'entrée"), ('SORTIE', 'Modification heure de sortie'), ('LES_DEUX', 'Modification des deux heures')], default='LES_DEUX', max_length=10)),
                ('heure_entree_manuelle', models.TimeField(blank=True, null=True)),
                ('heure_sortie_manuelle', models.TimeField(blank=True, null=True)),
                ('raison', models.TextField(blank=True, null=True)),
                ('appliquee', models.BooleanField(default=True)),
                ('cree_par', models.CharField(blank=True, max_length=100, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Modification d'heure",
                'verbose_name_plural': "Modifications d'heures",
                'db_table': 'modification_heure',
                'ordering': ['date', 'userid'],
                'unique_together': {('userid', 'date')},
            },
        ),
    ]
