# Generated by Django 5.2.7 on 2026-01-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0014_modificationheure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModificationHeure',
        ),
    ]
