# Generated by Django 5.2.7 on 2026-01-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0015_delete_modificationheure'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeureComptabilisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='userid')),
                ('date', models.DateField()),
                ('heure_entree_comptabilisee', models.TimeField(blank=True, null=True)),
                ('heure_sortie_comptabilisee', models.TimeField(blank=True, null=True)),
                ('modifie_manuellement', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Heure comptabilisée',
                'verbose_name_plural': 'Heures comptabilisées',
                'db_table': 'heure_comptabilisee',
                'ordering': ['date', 'userid'],
                'unique_together': {('userid', 'date')},
            },
        ),
    ]
