# Generated by Django 5.2.7 on 2026-01-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0016_heurecomptabilisee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeureComptabilisee',
        ),
    ]
