# Generated by Django 5.2.7 on 2026-01-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0017_delete_heurecomptabilisee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomaliePointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='userid')),
                ('date', models.DateField()),
                ('heure_entree_modifiee', models.TimeField(blank=True, null=True)),
                ('heure_sortie_modifiee', models.TimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('modifie_par', models.CharField(blank=True, max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anomalie de pointage',
                'verbose_name_plural': 'Anomalies de pointage',
                'db_table': 'anomalie_pointage',
                'ordering': ['date', 'userid'],
                'unique_together': {('userid', 'date')},
            },
        ),
    ]
