# Generated by Django 5.2.7 on 2026-01-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0018_anomaliepointage'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='est_jour_paiement',
            field=models.BooleanField(default=False),
        ),
    ]
