# Generated by Django 5.2.7 on 2026-01-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0019_date_est_jour_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='horairesection',
            name='sortie_samedi_paiement',
            field=models.DecimalField(decimal_places=2, default=13.0, help_text='Heure de sortie le samedi de paiement en format décimal', max_digits=4),
        ),
        migrations.AddField(
            model_name='horairesection',
            name='sortie_vendredi_paiement',
            field=models.DecimalField(decimal_places=2, default=17.33, help_text='Heure de sortie le vendredi de paiement en format décimal', max_digits=4),
        ),
    ]
