# Generated by Django 5.2.7 on 2026-01-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0020_horairesection_sortie_samedi_paiement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnomaliePointage',
        ),
    ]
