# Generated by Django 5.2.7 on 2026-01-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0021_delete_anomaliepointage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='userid')),
                ('date', models.DateField()),
                ('checktype', models.CharField(blank=True, max_length=10, null=True)),
                ('heure_brute_entree', models.TimeField(blank=True, null=True)),
                ('heure_brute_sortie', models.TimeField(blank=True, null=True)),
                ('heure_reelle_entree', models.TimeField(blank=True, null=True)),
                ('heure_reelle_sortie', models.TimeField(blank=True, null=True)),
                ('heure_comptabilisee_entree', models.TimeField(blank=True, null=True)),
                ('heure_comptabilisee_sortie', models.TimeField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('absence_entree', "N'a pas fait d'entrée"), ('absence_sortie', "N'a pas fait de sortie"), ('entree_non_conforme', 'Entrée non conforme'), ('sortie_non_conforme', 'Sortie non conforme'), ('ok', 'OK')], default='absence_entree', max_length=30)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('code_date', models.CharField(blank=True, max_length=10, null=True)),
                ('corrigee', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anomalie',
                'verbose_name_plural': 'Anomalies',
                'db_table': 'anomalie',
                'ordering': ['date', 'userid'],
                'unique_together': {('userid', 'date')},
            },
        ),
    ]
