# Generated by Django 5.2.7 on 2026-01-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0022_anomalie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='etat',
            field=models.CharField(choices=[('absence_entree', "N'a pas fait d'entrée"), ('absence_sortie', "N'a pas fait de sortie"), ('absence_entree_sortie', "N'a fait ni entrée ni sortie"), ('inversion_entree_sortie', 'Entrée et sortie inversées'), ('ok', 'OK')], default='absence_entree', max_length=30),
        ),
    ]
