# Generated by Django 5.2.7 on 2026-01-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0023_alter_anomalie_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='heure_rectifiee_entree',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='heure_rectifiee_sortie',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
