# Generated by Django 5.2.7 on 2026-01-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0024_anomalie_heure_rectifiee_entree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalie',
            name='heure_rectifiee_entree',
        ),
        migrations.RemoveField(
            model_name='anomalie',
            name='heure_rectifiee_sortie',
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='etat',
            field=models.CharField(choices=[('absence_entree', "N'a pas fait d'entrée"), ('absence_sortie', "N'a pas fait de sortie"), ('entree_non_conforme', 'Entrée non conforme'), ('sortie_non_conforme', 'Sortie non conforme'), ('ok', 'OK')], default='absence_entree', max_length=30),
        ),
    ]
