# Generated by Django 5.2.7 on 2026-01-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0025_remove_anomalie_heure_rectifiee_entree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalie',
            old_name='heure_comptabilisee_entree',
            new_name='heure_rectifiee_entree',
        ),
        migrations.RenameField(
            model_name='anomalie',
            old_name='heure_comptabilisee_sortie',
            new_name='heure_rectifiee_sortie',
        ),
        migrations.RemoveField(
            model_name='anomalie',
            name='checktype',
        ),
        migrations.RemoveField(
            model_name='anomalie',
            name='corrigee',
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='etat',
            field=models.CharField(choices=[('pas_entree', "Pas d'entrée"), ('pas_sortie', 'Pas de sortie'), ('non_conforme', 'Entrée et sortie non conformes'), ('ok', 'OK')], default='pas_entree', max_length=30),
        ),
    ]
