# Generated by Django 5.2.7 on 2026-01-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0026_rename_heure_comptabilisee_entree_anomalie_heure_rectifiee_entree_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalie',
            options={'ordering': ['-date', 'section', 'userid'], 'verbose_name': 'Anomalie', 'verbose_name_plural': 'Anomalies'},
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='etat',
            field=models.CharField(choices=[('pas_entree', "Pas d'entrée"), ('pas_sortie', 'Pas de sortie'), ('entree_sortie_non_conformes', 'Entrée et sortie non conformes'), ('ok', 'OK')], default='pas_entree', max_length=50),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='userid',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='anomalie',
            table='presence_anomalie',
        ),
    ]
