# Generated by Django 5.2.7 on 2026-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0027_alter_anomalie_options_alter_anomalie_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='synchronise_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
