# Generated by Django 5.2.7 on 2026-02-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0028_anomalie_synchronise_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='etat',
            field=models.CharField(choices=[('pas_entree', 'Entrée manquante'), ('pas_sortie', 'Sortie manquante'), ('ok', 'OK')], default='pas_entree', max_length=50),
        ),
    ]
