# Generated by Django 5.2.7 on 2026-02-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0029_alter_anomalie_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='etat',
            field=models.CharField(choices=[('pas_entree', "Pas d'entrée"), ('pas_sortie', 'Pas de sortie'), ('entree_sortie_non_conformes', 'Entrée et sortie non conformes'), ('ok', 'OK')], default='pas_entree', max_length=50),
        ),
    ]
