# Generated by Django 5.2.7 on 2026-02-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0033_alter_evenement_type_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='pointages_bruts',
            field=models.JSONField(blank=True, default=list, help_text='Liste des pointages bruts du jour', null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(choices=[('X', 'Travail normal'), ('RM', 'Repos Médical'), ('HP', 'Hospitalisation'), ('RC', 'Repos de convalescence'), ('ANO', 'Absence Non Autorisée'), ('CP', 'Congé Payé'), ('EF', 'Événement familial'), ('F', 'Fonction (délégués)'), ('PS', 'Permission Spéciale'), ('A', 'Absent'), ('AUT', 'Autre')], default='X', max_length=10),
        ),
    ]
