# Generated by Django 5.2.7 on 2026-02-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0034_anomalie_pointages_bruts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalie',
            name='pointages_bruts',
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='etat',
            field=models.CharField(choices=[('pas_entree', "Pas d'entrée"), ('pas_sortie', 'Pas de sortie'), ('multiples_pointages', 'Pointages multiples'), ('ok', 'OK')], default='pas_entree', max_length=50),
        ),
    ]
