# Generated by Django 5.2.7 on 2026-02-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0035_remove_anomalie_pointages_bruts_alter_anomalie_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalie',
            name='pointages_bruts_json',
            field=models.JSONField(blank=True, help_text='Tous les pointages du jour [{time, checktype}, ...]', null=True),
        ),
    ]
