# Generated by Django 5.2.7 on 2026-03-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0036_anomalie_pointages_bruts_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbSection',
            fields=[
                ('sect_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100, unique=True, verbose_name='Section réelle')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'db_section',
                'ordering': ['section_name'],
            },
        ),
        migrations.CreateModel(
            name='UserSection',
            fields=[
                ('userid', models.IntegerField(db_column='userid', primary_key=True, serialize=False, verbose_name='ID employé (UserInfo)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='presence.dbsection', verbose_name='Section réelle')),
            ],
            options={
                'verbose_name': 'Affectation section',
                'verbose_name_plural': 'Affectations sections',
                'db_table': 'user_section',
            },
        ),
    ]
