# Generated by Django 5.2.7 on 2026-03-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0037_dbsection_usersection'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersection',
            name='badgenumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersection',
            name='numero_matricule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
