# Generated by Django 5.2.7 on 2026-03-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0038_usersection_badgenumber_usersection_numero_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersection',
            name='numero_matricule',
        ),
    ]
