# Generated by Django 5.2.7 on 2026-03-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0039_remove_usersection_numero_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersection',
            name='section',
        ),
        migrations.DeleteModel(
            name='DbSection',
        ),
        migrations.DeleteModel(
            name='UserSection',
        ),
    ]
