# Generated by Django 5.2.7 on 2026-03-05 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0040_remove_usersection_section_delete_dbsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.CharField(max_length=150, unique=True, verbose_name='Nom de la section')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'db_section',
                'ordering': ['nom_section'],
            },
        ),
        migrations.CreateModel(
            name='UserSection',
            fields=[
                ('userid', models.IntegerField(db_column='userid', primary_key=True, serialize=False, verbose_name='ID utilisateur')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='presence.section')),
            ],
            options={
                'verbose_name': 'Section utilisateur',
                'verbose_name_plural': 'Sections utilisateurs',
                'db_table': 'db_user_section',
            },
        ),
    ]
