# Generated by Django 5.2.7 on 2026-03-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0041_section_usersection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='pointages_bruts_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horairesection',
            name='heure_entree',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='horairesection',
            name='heure_sortie',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='horairesection',
            name='sortie_samedi',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='horairesection',
            name='sortie_samedi_paiement',
            field=models.DecimalField(decimal_places=2, default=13.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='horairesection',
            name='sortie_vendredi_paiement',
            field=models.DecimalField(decimal_places=2, default=17.33, max_digits=4),
        ),
    ]
