# Generated by Django 5.2.7 on 2026-03-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0042_alter_anomalie_pointages_bruts_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='pointages_bruts_json',
            field=models.JSONField(blank=True, help_text='Tous les pointages du jour [{time, checktype}, ...]', null=True),
        ),
        migrations.AlterField(
            model_name='horairesection',
            name='heure_entree',
            field=models.DecimalField(decimal_places=2, help_text="Heure d'entrée en format décimal (ex: 7.50 = 7h30)", max_digits=4),
        ),
        migrations.AlterField(
            model_name='horairesection',
            name='heure_sortie',
            field=models.DecimalField(decimal_places=2, help_text='Heure de sortie en format décimal (ex: 17.83 = 17h50)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='horairesection',
            name='sortie_samedi',
            field=models.DecimalField(decimal_places=2, help_text='Heure de sortie le samedi en format décimal', max_digits=4),
        ),
        migrations.AlterField(
            model_name='horairesection',
            name='sortie_samedi_paiement',
            field=models.DecimalField(decimal_places=2, default=13.0, help_text='Heure de sortie le samedi de paiement en format décimal', max_digits=4),
        ),
        migrations.AlterField(
            model_name='horairesection',
            name='sortie_vendredi_paiement',
            field=models.DecimalField(decimal_places=2, default=17.33, help_text='Heure de sortie le vendredi de paiement en format décimal', max_digits=4),
        ),
    ]
