# Generated by Django 5.2.7 on 2026-03-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0043_alter_anomalie_pointages_bruts_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttParam',
            fields=[
                ('attparamid', models.AutoField(db_column='AttParamId', primary_key=True, serialize=False)),
                ('paraname', models.CharField(blank=True, db_column='ParaName', max_length=50, null=True)),
                ('paravalue', models.IntegerField(blank=True, db_column='ParaValue', null=True)),
            ],
            options={
                'db_table': 'AttParam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('deptid', models.AutoField(db_column='DEPTID', primary_key=True, serialize=False)),
                ('deptname', models.CharField(blank=True, db_column='DEPTNAME', max_length=100, null=True)),
            ],
            options={
                'db_table': 'DEPARTMENTS',
                'managed': False,
            },
        ),
    ]
