# Generated by Django 5.2.7 on 2026-03-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0044_attparam_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinout',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': True},
        ),
    ]
