# Generated by Django 5.2.7 on 2026-03-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0045_alter_checkinout_options_alter_userinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinout',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='attparam',
            table='attparam',
        ),
    ]
