# Generated by Django 5.2.7 on 2026-04-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0046_alter_checkinout_options_alter_userinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departments',
            table='departments',
        ),
    ]
