# Generated by Django 5.2.7 on 2026-04-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0047_alter_departments_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('section', models.CharField(blank=True, help_text='Laisser vide = toutes les sections', max_length=100, null=True)),
                ('heure_entree', models.TimeField(blank=True, help_text="Surcharge heure d'entrée (optionnel)", null=True)),
                ('heure_sortie', models.TimeField(blank=True, help_text='Surcharge heure de sortie', null=True)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'horaire_exception',
                'ordering': ['-date'],
                'unique_together': {('date', 'section')},
            },
        ),
    ]
