# Generated by Django 5.2.7 on 2026-04-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0048_horaireexception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(choices=[('X', 'Travail normal'), ('RM', 'Repos Médical'), ('HP', 'Hospitalisation'), ('RC', 'Repos de convalescence'), ('ANO', 'Absence Non Autorisée'), ('CP', 'Congé Payé'), ('EF', 'Événement familial'), ('F', 'Fonction (délégués)'), ('PS', 'Permission Spéciale'), ('A', 'Absent'), ('HA', 'Allaitement'), ('OS', 'Ostie'), ('AUT', 'Autre')], default='X', max_length=10),
        ),
    ]
