# Generated by Django 5.2.7 on 2026-05-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0051_alter_evenement_type_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeFermeture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('mois', models.IntegerField(verbose_name='Mois (1-12)')),
                ('date_fermeture', models.DateField(verbose_name='Date de fermeture')),
                ('motif', models.CharField(blank=True, max_length=200, verbose_name='Motif')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fermeture de période',
                'verbose_name_plural': 'Fermetures de période',
                'db_table': 'presence_periode_fermeture',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('annee', 'mois')},
            },
        ),
    ]
