# Generated by Django 5.2.7 on 2026-06-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0052_periodefermeture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(choices=[('X', 'Travail normal'), ('A', 'Absent'), ('ANO', 'Absence Non Autorisée'), ('AMP', ''), ('CE', "Congé d'éducation"), ('CM', 'Congé de matérnité'), ('CP', 'Congé Payé'), ('EF', 'Événement familial'), ('F', 'Fonction (délégués)'), ('HA', 'Allaitement'), ('HP', 'Hospitalisation'), ('MP', 'Mise à pied'), ('OS', 'Ostie'), ('PS', 'Permission Spéciale'), ('RC', 'Repos de convalescence'), ('RM', 'Repos Médical'), ('AUT', 'Autre')], default='X', max_length=10),
        ),
    ]
