# Generated by Django 5.2.7 on 2026-06-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0053_alter_evenement_type_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='etat',
            field=models.CharField(choices=[('pas_entree', "Pas d'entrée"), ('pas_sortie', 'Pas de sortie'), ('multiples_pointages', 'Pointages multiples'), ('retard_sortie', 'Retard de sortie'), ('ok', 'OK')], default='pas_entree', max_length=50),
        ),
    ]
