# Generated by Django 5.2.7 on 2026-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0059_alter_anomalie_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='etat',
            field=models.CharField(choices=[('pas_entree', "Pas d'entrée"), ('pas_sortie', 'Pas de sortie'), ('multiples_pointages', 'Pointages multiples'), ('retard_sortie', 'Retard de sortie'), ('entree_egale_sortie', 'Entrée = Sortie'), ('sortie_avant_entree', 'Sortie avant entrée'), ('ok', 'OK')], default='pas_entree', max_length=50),
        ),
    ]
